artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/18efd0efc5ff4c6a8b48b82799f9ed21/artifacts
deleted_time: 1749147522499
end_time: 1749147331564
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: 18efd0efc5ff4c6a8b48b82799f9ed21
run_name: exultant-fish-752
run_uuid: 18efd0efc5ff4c6a8b48b82799f9ed21
source_name: ''
source_type: 4
source_version: ''
start_time: 1749147241507
status: 4
tags: []
user_id: arman
