artifact_location: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0
creation_time: 1749145449319
experiment_id: '0'
last_update_time: 1749145449319
lifecycle_stage: active
name: Default
