Projektarbeit 24/25: Enemy.SpawnlingAutoRegister Class Reference
Enemy.SpawnlingAutoRegister Class Reference
Private Member Functions
void Awake ()
Unity Awake method called when the GameObject is initialized. Sets up the EnemyDeathReporter and registers the Spawnling with the current room's spawner.
Detailed Description
Definition at line 9 of file SpawnlingAutoRegister.cs.
Member Function Documentation
Awake()
void Enemy.SpawnlingAutoRegister.Awake () inline private
Unity Awake method called when the GameObject is initialized. Sets up the EnemyDeathReporter and registers the Spawnling with the current room's spawner.
Definition at line 15 of file SpawnlingAutoRegister.cs.
References Manager.GameManagerVoronoi.CurrentRoom, Manager.GameManagerVoronoi.Instance, Spawning.BossSpawnerVoronoi.RegisterBossMinionDeath(), Spawning.BossSpawnerVoronoi.RegisterBossMinionSpawn(), Spawning.EnemySpawnerVoronoi.RegisterEnemyMinionDeath(), and Spawning.EnemySpawnerVoronoi.RegisterEnemyMinionSpawn().
The documentation for this class was generated from the following file:
SpawnlingAutoRegister.cs