Projektarbeit 24/25: Enemy.EnemyDeathReporter Class Reference
Enemy.EnemyDeathReporter Class Reference
Reports the death of an enemy to a callback when destroyed. Prevents duplicate reports and avoids reporting during scene transitions.
Public Member Functions
void Init (int roomId, Action< int > onDeath)
Initializes the death reporter with the enemy's room ID and a callback.
void ReportDeath ()
Reports the enemy's death by invoking the callback, unless already reported or a scene change is occurring.
Static Public Member Functions
static void SetSceneChanging (bool value)
Sets the global scene-changing flag to prevent false reports.
Private Member Functions
void OnDestroy ()
Unity callback invoked when the GameObject is destroyed. Reports death if not already reported, unless caused by a scene change or invalid scene state.
Private Attributes
Action< int > _onDeath
Callback invoked when the enemy dies. Passes the room ID of the enemy.
int _roomId
The ID of the room this enemy belongs to.
bool _reported
Tracks whether death has already been reported for this enemy.
Static Private Attributes
static bool _sceneChanging
Indicates if the scene is currently changing to prevent false reports.
Detailed Description
Reports the death of an enemy to a callback when destroyed. Prevents duplicate reports and avoids reporting during scene transitions.
Definition at line 10 of file EnemyDeathReporter.cs.
Member Function Documentation
Init()
void Enemy.EnemyDeathReporter.Init (int roomId, Action< int > onDeath) inline
Initializes the death reporter with the enemy's room ID and a callback.
Parameters
roomId The ID of the room the enemy belongs to.
onDeath The callback to invoke when the enemy dies.
Definition at line 38 of file EnemyDeathReporter.cs.
References _onDeath, and _roomId.
Referenced by Spawning.BossSpawnerVoronoi.BossSpawnerVoronoi(), and Spawning.EnemySpawnerVoronoi.EnemySpawnerVoronoi().
OnDestroy()
void Enemy.EnemyDeathReporter.OnDestroy () inline private
Unity callback invoked when the GameObject is destroyed. Reports death if not already reported, unless caused by a scene change or invalid scene state.
Definition at line 65 of file EnemyDeathReporter.cs.
References _reported, _sceneChanging, and ReportDeath().
ReportDeath()
void Enemy.EnemyDeathReporter.ReportDeath () inline
Reports the enemy's death by invoking the callback, unless already reported or a scene change is occurring.
Definition at line 48 of file EnemyDeathReporter.cs.
References _onDeath, _reported, _roomId, and _sceneChanging.
Referenced by OnDestroy().
SetSceneChanging()
void Enemy.EnemyDeathReporter.SetSceneChanging (bool value) static
Sets the global scene-changing flag to prevent false reports.
Parameters
value True if the scene is changing; otherwise false.
References _sceneChanging.
Referenced by Manager.ButtonManager.ExitGame(), Interaction.LevelExitInteraction.Interact(), Manager.ButtonManager.LoadGame(), Manager.GameManagerVoronoi.Start(), and Manager.ButtonManager.StartGame().
Member Data Documentation
_onDeath
Action<int> Enemy.EnemyDeathReporter._onDeath private
Callback invoked when the enemy dies. Passes the room ID of the enemy.
Definition at line 16 of file EnemyDeathReporter.cs.
Referenced by Init(), and ReportDeath().
_reported
bool Enemy.EnemyDeathReporter._reported private
Tracks whether death has already been reported for this enemy.
Definition at line 26 of file EnemyDeathReporter.cs.
Referenced by OnDestroy(), and ReportDeath().
_roomId
int Enemy.EnemyDeathReporter._roomId private
The ID of the room this enemy belongs to.
Definition at line 21 of file EnemyDeathReporter.cs.
Referenced by Init(), and ReportDeath().
_sceneChanging
bool Enemy.EnemyDeathReporter._sceneChanging static private
Indicates if the scene is currently changing to prevent false reports.
Definition at line 31 of file EnemyDeathReporter.cs.
Referenced by OnDestroy(), ReportDeath(), and SetSceneChanging().
The documentation for this class was generated from the following file:
EnemyDeathReporter.cs