Projektarbeit 24/25: Interaction.DestroyableWallInteraction Class Reference
Interaction.DestroyableWallInteraction Class Reference
Interaction for a breakable wall that can only be damaged with a pickaxe. Shows short feedback, updates hit points, saves state, and disables itself when destroyed.
Public Member Functions
void InitializeFromSave ()
Loads hit points from the save and initializes the label text and color. Call once after edgeID is assigned.
void Interact (GameObject interactor)
Handles player interaction: checks for a pickaxe in the right hand, prompts for right-click, plays the swing, reduces HP, saves it, and destroys the wall at 0 HP.
void OnExit (GameObject interactor)
Clears the prompt and resets click state when the player leaves the wall.
bool ShouldRepeat ()
Returns whether Interact should be called every frame while in range. Always true for this interaction.
Public Attributes
int edgeID
Save index for this wall (maps to the destroyable wall lists in the save). Must be set before calling InitializeFromSave.
Private Member Functions
System.Collections.IEnumerator HideLifeText ()
Briefly shows the HP labels, then hides them.
System.Collections.IEnumerator DisableAfterDelay (float delay)
Waits for the swing to finish, then disables the wall object.
Private Attributes
TextMeshPro lifeTextFront
Front-facing hit point label.
TextMeshPro lifeTextBack
Back-facing hit point label.
int _hitPoints
Current remaining hit points.
Color _currentColor
Current color used for the hit point labels.
bool _waitingForClick
True, while we wait for the player's next click to swing.
float _nextHitTime
Cooldown time (next allowed hit) based on swing duration.
bool _destroyScheduled
Ensures we only schedule destruction once when HP reaches zero.
Detailed Description
Interaction for a breakable wall that can only be damaged with a pickaxe. Shows short feedback, updates hit points, saves state, and disables itself when destroyed.
Definition at line 14 of file DestroyableWallInteraction.cs.
Member Function Documentation
DisableAfterDelay()
System.Collections.IEnumerator Interaction.DestroyableWallInteraction.DisableAfterDelay (float delay) inline private
Waits for the swing to finish, then disables the wall object.
Parameters
delay Delay before disabling, typically the swing duration.
Definition at line 180 of file DestroyableWallInteraction.cs.
Referenced by Interact().
HideLifeText()
System.Collections.IEnumerator Interaction.DestroyableWallInteraction.HideLifeText () inline private
Briefly shows the HP labels, then hides them.
Definition at line 169 of file DestroyableWallInteraction.cs.
References lifeTextBack, and lifeTextFront.
Referenced by Interact().
InitializeFromSave()
void Interaction.DestroyableWallInteraction.InitializeFromSave () inline
Loads hit points from the save and initializes the label text and color. Call once after edgeID is assigned.
Definition at line 61 of file DestroyableWallInteraction.cs.
References _currentColor, _hitPoints, edgeID, Manager.SaveSystemManager.GetDestroyableWallHealth(), lifeTextBack, and lifeTextFront.
Interact()
void Interaction.DestroyableWallInteraction.Interact (GameObject interactor) inline
Handles player interaction: checks for a pickaxe in the right hand, prompts for right-click, plays the swing, reduces HP, saves it, and destroys the wall at 0 HP.
Parameters
interactor The player GameObject.
Implements Interfaces.IInteractable.
Definition at line 86 of file DestroyableWallInteraction.cs.
References _currentColor, _destroyScheduled, _hitPoints, _nextHitTime, _waitingForClick, DisableAfterDelay(), edgeID, HideLifeText(), Manager.UIManager.HidePanel(), Manager.UIManager.Instance, lifeTextBack, lifeTextFront, Items.Pickaxe, Manager.SaveSystemManager.SetDestroyableWallActive(), Manager.SaveSystemManager.SetDestroyableWallHealth(), and Manager.UIManager.ShowPanel().
OnExit()
void Interaction.DestroyableWallInteraction.OnExit (GameObject interactor) inline
Clears the prompt and resets click state when the player leaves the wall.
Parameters
interactor The player GameObject.
Implements Interfaces.IInteractable.
Definition at line 153 of file DestroyableWallInteraction.cs.
References _waitingForClick, Manager.UIManager.HidePanel(), and Manager.UIManager.Instance.
ShouldRepeat()
bool Interaction.DestroyableWallInteraction.ShouldRepeat ()
Returns whether Interact should be called every frame while in range. Always true for this interaction.
Returns
True to keep interacting each frame.
Implements Interfaces.IInteractable.
Member Data Documentation
_currentColor
Color Interaction.DestroyableWallInteraction._currentColor private
Current color used for the hit point labels.
Definition at line 40 of file DestroyableWallInteraction.cs.
Referenced by InitializeFromSave(), and Interact().
_destroyScheduled
bool Interaction.DestroyableWallInteraction._destroyScheduled private
Ensures we only schedule destruction once when HP reaches zero.
Definition at line 55 of file DestroyableWallInteraction.cs.
Referenced by Interact().
_hitPoints
int Interaction.DestroyableWallInteraction._hitPoints private
Current remaining hit points.
Definition at line 35 of file DestroyableWallInteraction.cs.
Referenced by InitializeFromSave(), and Interact().
_nextHitTime
float Interaction.DestroyableWallInteraction._nextHitTime private
Cooldown time (next allowed hit) based on swing duration.
Definition at line 50 of file DestroyableWallInteraction.cs.
Referenced by Interact().
_waitingForClick
bool Interaction.DestroyableWallInteraction._waitingForClick private
True, while we wait for the player's next click to swing.
Definition at line 45 of file DestroyableWallInteraction.cs.
Referenced by Interact(), and OnExit().
edgeID
int Interaction.DestroyableWallInteraction.edgeID
Save index for this wall (maps to the destroyable wall lists in the save). Must be set before calling InitializeFromSave.
Definition at line 30 of file DestroyableWallInteraction.cs.
Referenced by InitializeFromSave(), and Interact().
lifeTextBack
TextMeshPro Interaction.DestroyableWallInteraction.lifeTextBack private
Back-facing hit point label.
Definition at line 24 of file DestroyableWallInteraction.cs.
Referenced by HideLifeText(), InitializeFromSave(), and Interact().
lifeTextFront
TextMeshPro Interaction.DestroyableWallInteraction.lifeTextFront private
Front-facing hit point label.
Definition at line 19 of file DestroyableWallInteraction.cs.
Referenced by HideLifeText(), InitializeFromSave(), and Interact().
The documentation for this class was generated from the following file:
DestroyableWallInteraction.cs