Projektarbeit 24/25: Spawning.EnemySpawnerVoronoi Class Reference
Spawning.EnemySpawnerVoronoi Class Reference
Spawns and manages enemies in Voronoi-based dungeon rooms. Enemies are spawned based on the room's size (incircle radius).
Public Member Functions
EnemySpawnerVoronoi (List< Room > enemyRooms, List< GameObject > enemyPrefabs, Transform parent)
Initializes the enemy spawner by instantiating enemies in all enemy rooms. The number of enemies depends on the room size (incircle radius).
void ActivateEnemyInRoom (Room room)
Activates all enemies in the given room when the player enters it.
Static Public Member Functions
static void RegisterEnemyMinionSpawn (int roomId)
increases amount of living enemies in the corresponding room because there are enemies that can spawn smaller enemies to their help
static void RegisterEnemyMinionDeath (int roomId)
decreases amount of living enemies in the corresponding room because there are enemies that can spawn smaller enemies to their help
Private Member Functions
void OnEnemyDied (int roomId)
function that tracks if all enemies in the corresponding room have been defeated, also decreases living amount
void IncrementAlive (int roomId)
function that increases the tracker of the living enemies per room
Private Attributes
readonly Dictionary< int, List< GameObject > > _enemyInstancesPerRoom = new()
Stores all enemies per room, keyed by room ID.
readonly Dictionary< int, int > _alivePerRoom = new()
stores all enemies that are alive per room, keyed by room ID.
Static Private Attributes
static EnemySpawnerVoronoi _instance
static instance of the spawner
Detailed Description
Spawns and manages enemies in Voronoi-based dungeon rooms. Enemies are spawned based on the room's size (incircle radius).
Definition at line 13 of file EnemySpawnerVoronoi.cs.
Constructor & Destructor Documentation
EnemySpawnerVoronoi()
Spawning.EnemySpawnerVoronoi.EnemySpawnerVoronoi (List< Room > enemyRooms, List< GameObject > enemyPrefabs, Transform parent) inline
Initializes the enemy spawner by instantiating enemies in all enemy rooms. The number of enemies depends on the room size (incircle radius).
Parameters
enemyRooms List of enemy rooms
enemyPrefabs List of enemy prefabs to randomly choose from
parent Parent transform under which the enemies are spawned
Definition at line 37 of file EnemySpawnerVoronoi.cs.
References _alivePerRoom, _enemyInstancesPerRoom, _instance, Enemy.EnemyLevelScaler.Apply(), Enemy.EnemyDeathReporter.Init(), and OnEnemyDied().
Member Function Documentation
ActivateEnemyInRoom()
void Spawning.EnemySpawnerVoronoi.ActivateEnemyInRoom (Room room) inline
Activates all enemies in the given room when the player enters it.
Parameters
room Room whose enemies should be activated
Definition at line 87 of file EnemySpawnerVoronoi.cs.
References _enemyInstancesPerRoom, and Dungeon.Room.ID.
IncrementAlive()
void Spawning.EnemySpawnerVoronoi.IncrementAlive (int roomId) inline private
function that increases the tracker of the living enemies per room
Parameters
roomId id of room where living amount should be increased
Definition at line 135 of file EnemySpawnerVoronoi.cs.
References _alivePerRoom.
OnEnemyDied()
void Spawning.EnemySpawnerVoronoi.OnEnemyDied (int roomId) inline private
function that tracks if all enemies in the corresponding room have been defeated, also decreases living amount
Parameters
roomId room id of the room where an enemies have been defeated
Definition at line 100 of file EnemySpawnerVoronoi.cs.
References _alivePerRoom, Manager.EventManager.Instance, and Manager.EventManager.TriggerOpenDoors().
Referenced by EnemySpawnerVoronoi().
RegisterEnemyMinionDeath()
void Spawning.EnemySpawnerVoronoi.RegisterEnemyMinionDeath (int roomId) inline static
decreases amount of living enemies in the corresponding room because there are enemies that can spawn smaller enemies to their help
Parameters
roomId id of room where living amount should be decreased
Definition at line 126 of file EnemySpawnerVoronoi.cs.
References _instance.
Referenced by Enemy.SpawnlingAutoRegister.Awake().
RegisterEnemyMinionSpawn()
void Spawning.EnemySpawnerVoronoi.RegisterEnemyMinionSpawn (int roomId) inline static
increases amount of living enemies in the corresponding room because there are enemies that can spawn smaller enemies to their help
Parameters
roomId id of room where living amount should be increased
Definition at line 117 of file EnemySpawnerVoronoi.cs.
References _instance.
Referenced by Enemy.SpawnlingAutoRegister.Awake().
Member Data Documentation
_alivePerRoom
readonly Dictionary<int, int> Spawning.EnemySpawnerVoronoi._alivePerRoom = new() private
stores all enemies that are alive per room, keyed by room ID.
Definition at line 23 of file EnemySpawnerVoronoi.cs.
Referenced by EnemySpawnerVoronoi(), IncrementAlive(), and OnEnemyDied().
_enemyInstancesPerRoom
readonly Dictionary<int, List<GameObject> > Spawning.EnemySpawnerVoronoi._enemyInstancesPerRoom = new() private
Stores all enemies per room, keyed by room ID.
Definition at line 18 of file EnemySpawnerVoronoi.cs.
Referenced by ActivateEnemyInRoom(), and EnemySpawnerVoronoi().
_instance
EnemySpawnerVoronoi Spawning.EnemySpawnerVoronoi._instance static private
static instance of the spawner
Definition at line 28 of file EnemySpawnerVoronoi.cs.
Referenced by EnemySpawnerVoronoi(), RegisterEnemyMinionDeath(), and RegisterEnemyMinionSpawn().
The documentation for this class was generated from the following file:
EnemySpawnerVoronoi.cs