Projektarbeit 24/25: Manager.ButtonManager Class Reference
Manager.ButtonManager Class Reference
Handles menu button actions: start, load, save, and exit. Sets a scene-changing flag to avoid enemy death reports during scene switches.
Public Member Functions
void StartGame ()
Starts a new game: creates a new save with a random seed and loads the main scene.
void LoadGame ()
Loads an existing save and opens the main scene if a save file exists.
void ExitGame ()
Exits the game (or stops Play Mode in the editor).
void SaveGame ()
Saves the current player state: position, view direction, camera direction, inventory, equipment, and stats.
Detailed Description
Handles menu button actions: start, load, save, and exit. Sets a scene-changing flag to avoid enemy death reports during scene switches.
Definition at line 12 of file ButtonManager.cs.
Member Function Documentation
ExitGame()
void Manager.ButtonManager.ExitGame () inline
Exits the game (or stops Play Mode in the editor).
Definition at line 55 of file ButtonManager.cs.
References Enemy.EnemyDeathReporter.SetSceneChanging().
LoadGame()
void Manager.ButtonManager.LoadGame () inline
Loads an existing save and opens the main scene if a save file exists.
Definition at line 32 of file ButtonManager.cs.
References Manager.SaveSystemManager.Load(), Manager.SaveSystemManager.SaveData, and Enemy.EnemyDeathReporter.SetSceneChanging().
SaveGame()
void Manager.ButtonManager.SaveGame () inline
Saves the current player state: position, view direction, camera direction, inventory, equipment, and stats.
Definition at line 74 of file ButtonManager.cs.
References Manager.SaveSystemManager.Save(), Manager.SaveSystemManager.SetCamRotation(), Manager.SaveSystemManager.SetEquipment(), Manager.SaveSystemManager.SetInventory(), Manager.SaveSystemManager.SetPlayerPosition(), Manager.SaveSystemManager.SetPlayerRotation(), and Manager.SaveSystemManager.SetStats().
StartGame()
void Manager.ButtonManager.StartGame () inline
Starts a new game: creates a new save with a random seed and loads the main scene.
Definition at line 17 of file ButtonManager.cs.
References Enemy.EnemyDeathReporter.SetSceneChanging(), and Manager.SaveSystemManager.StartNewRun().
The documentation for this class was generated from the following file:
ButtonManager.cs