Projektarbeit 24/25: Controller.VignetteController Class Reference
Controller.VignetteController Class Reference
Controller for managing the health vignette behaviour depending on health state.
Public Attributes
Color fullHealthColor = new(0, 0, 0, 0)
vignette color for full health state
Color halfHealthColor = new(1, 0.5f, 0, 0.6f)
vignette color for half-health state
Color lowHealthColor = new(1, 0, 0, 0.75f)
vignette color for low health state
Private Member Functions
void Start ()
start event of this monobehaviour and setting the member variables of volume & vignette
void Update ()
update function that checks and updates the player stats to change the vignette style depending on the health value
Private Attributes
float lerpSpeed = 0.6f
private variable that changes the lerping speed
Volume _volume
volume on which we will set the vignette
Stats.Stats _playerStats
stats of the player that our vignette depends on
Vignette _vignette
actual vignette member that will be worked with
Detailed Description
Controller for managing the health vignette behaviour depending on health state.
Definition at line 10 of file VignetteController.cs.
Member Function Documentation
Start()
void Controller.VignetteController.Start () inline private
start event of this monobehaviour and setting the member variables of volume & vignette
Definition at line 51 of file VignetteController.cs.
References _vignette, and _volume.
Update()
void Controller.VignetteController.Update () inline private
update function that checks and updates the player stats to change the vignette style depending on the health value
Definition at line 72 of file VignetteController.cs.
References _playerStats, _vignette, fullHealthColor, halfHealthColor, lerpSpeed, and lowHealthColor.
Member Data Documentation
_playerStats
Stats.Stats Controller.VignetteController._playerStats private
stats of the player that our vignette depends on
Definition at line 41 of file VignetteController.cs.
Referenced by Update().
_vignette
Vignette Controller.VignetteController._vignette private
actual vignette member that will be worked with
Definition at line 46 of file VignetteController.cs.
Referenced by Start(), and Update().
_volume
Volume Controller.VignetteController._volume private
volume on which we will set the vignette
Definition at line 36 of file VignetteController.cs.
Referenced by Start().
fullHealthColor
Color Controller.VignetteController.fullHealthColor = new(0, 0, 0, 0)
vignette color for full health state
Definition at line 21 of file VignetteController.cs.
Referenced by Update().
halfHealthColor
Color Controller.VignetteController.halfHealthColor = new(1, 0.5f, 0, 0.6f)
vignette color for half-health state
Definition at line 26 of file VignetteController.cs.
Referenced by Update().
lerpSpeed
float Controller.VignetteController.lerpSpeed = 0.6f private
private variable that changes the lerping speed
Definition at line 16 of file VignetteController.cs.
Referenced by Update().
lowHealthColor
Color Controller.VignetteController.lowHealthColor = new(1, 0, 0, 0.75f)
vignette color for low health state
Definition at line 31 of file VignetteController.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
VignetteController.cs