Projektarbeit 24/25: Dungeon.OpenDoor Class Reference
Dungeon.OpenDoor Class Reference
Listens for open and close events from the EventManager and toggles the door's state accordingly.
Public Attributes
bool isBossDoor
Flag to check a boss door.
Private Member Functions
void Start ()
Subscribes to the open and close door events and initializes references to the collider and door child.
void OnDestroy ()
Unsubscribes from the events to avoid memory leaks when the object is destroyed.
void Open ()
Opens the door by disabling the child door GameObject and the parent's collider.
void Close ()
Closes the door by enabling the child door GameObject and the parent's collider.
Private Attributes
Collider _parentCollider
Collider on the parent object, used to control collision when the door is opened or closed.
GameObject _doorChild
The child GameObject representing the actual door to enable or disable.
Detailed Description
Listens for open and close events from the EventManager and toggles the door's state accordingly.
Definition at line 9 of file OpenDoor.cs.
Member Function Documentation
Close()
void Dungeon.OpenDoor.Close () inline private
Closes the door by enabling the child door GameObject and the parent's collider.
Definition at line 88 of file OpenDoor.cs.
References _doorChild.
Referenced by OnDestroy(), and Start().
OnDestroy()
void Dungeon.OpenDoor.OnDestroy () inline private
Unsubscribes from the events to avoid memory leaks when the object is destroyed.
Definition at line 59 of file OpenDoor.cs.
References Close(), isBossDoor, Manager.EventManager.OnCloseBossDoors, Manager.EventManager.OnCloseDoors, Manager.EventManager.OnOpenBossDoors, Manager.EventManager.OnOpenDoors, and Open().
Open()
void Dungeon.OpenDoor.Open () inline private
Opens the door by disabling the child door GameObject and the parent's collider.
Definition at line 76 of file OpenDoor.cs.
References _doorChild.
Referenced by OnDestroy(), and Start().
Start()
void Dungeon.OpenDoor.Start () inline private
Subscribes to the open and close door events and initializes references to the collider and door child.
Definition at line 29 of file OpenDoor.cs.
References _doorChild, _parentCollider, Close(), isBossDoor, Manager.EventManager.OnCloseBossDoors, Manager.EventManager.OnCloseDoors, Manager.EventManager.OnOpenBossDoors, Manager.EventManager.OnOpenDoors, and Open().
Member Data Documentation
_doorChild
GameObject Dungeon.OpenDoor._doorChild private
The child GameObject representing the actual door to enable or disable.
Definition at line 19 of file OpenDoor.cs.
Referenced by Close(), Open(), and Start().
_parentCollider
Collider Dungeon.OpenDoor._parentCollider private
Collider on the parent object, used to control collision when the door is opened or closed.
Definition at line 14 of file OpenDoor.cs.
Referenced by Start().
isBossDoor
bool Dungeon.OpenDoor.isBossDoor
Flag to check a boss door.
Definition at line 24 of file OpenDoor.cs.
Referenced by OnDestroy(), and Start().
The documentation for this class was generated from the following file:
OpenDoor.cs