Projektarbeit 24/25: Manager.SaveSystemManager Class Reference
Manager.SaveSystemManager Class Reference
Manages saving and loading of game data and exposes helpers to read and update the current save.
Static Public Member Functions
static void Save ()
Serializes SaveData to JSON and writes it to disk.
static void Load ()
Loads save data from disk if it exists; otherwise keeps SaveData null and logs a message.
static void StartNewRun (int newSeed)
Creates a fresh save for a new run and writes it immediately.
static void AdvanceLevel (int newSeed)
Advances to the next level, updates the seed, and resets per-level fields.
static int GetSeed ()
Gets the current seed.
static int GetLevel ()
Gets the current level.
static int GetCurrentRoomID ()
Gets the current room id.
static void SetCurrentRoomID (int id)
Sets the current room id.
static bool GetBossRoomOpen ()
Gets whether the boss room door is open.
static void SetBossRoomOpen (bool open)
Sets whether the boss room door is open.
static bool GetBossCleared ()
Gets whether the boss fight is cleared.
static void SetBossCleared (bool cleared)
Sets whether the boss fight is cleared.
static List< bool > GetVisitedRooms ()
Gets the visited flags list for all rooms.
static void InitializeVisitedRooms (int roomCount)
Initializes the visited list with the given room count (all false).
static void SetRoomVisited (int roomId, bool visited)
Sets the visited state for a room id (safe bounds check).
static List< bool > GetDestroyableWallsActive ()
Gets the active flags list for destroyable walls (creates if null).
static void SetDestroyableWallActive (int idx, bool active)
Sets the active flag for a destroyable wall by index (safe bounds check).
static List< int > GetDestroyableWallsHealth ()
Gets the health list for destroyable walls (creates if null).
static void SetDestroyableWallHealth (int idx, int hp)
Sets the health value for a destroyable wall by index (safe bounds check).
static int GetDestroyableWallHealth (int idx)
Gets the health for a destroyable wall by index, or 0 if out of range.
static Vector3 GetPlayerPosition ()
Gets the saved player position.
static void SetPlayerPosition (Vector3 pos)
Sets the saved player position.
static Vector3 GetPlayerRotation ()
Gets the saved player forward direction.
static void SetPlayerRotation (Vector3 direct)
Sets the saved player forward direction.
static Vector3 GetCamRotation ()
Gets the saved camera forward direction.
static void SetCamRotation (Vector3 direct)
Sets the saved camera forward direction.
static List< float > GetStats ()
static void SetStats (List< float > currStats, List< float > maxStats)
Sets current and max stats lists.
static bool IsCollectibleActive (int idx)
Gets whether a collectible at index is active. Grows the list if needed.
static void SetCollectibleActive (int idx, bool active)
Sets whether a collectible at index is active. Grows the list if needed.
static ItemInstance[,] GetInventory ()
Returns a 4x5 grid view of the inventory from the 1D array, filtering out empty entries.
static void SetInventory (ItemInstance[,] grid)
Writes a 4x5 inventory grid back to the 1D save array.
static ItemInstance[,] GetEquipment ()
Returns a 3x2 grid view of the equipment from the 1D array, filtering out empty entries.
static void SetEquipment (ItemInstance[,] grid)
Writes a 3x2 equipment grid back to the 1D save array.
Static Public Attributes
static List< float >
Gets current and max stats lists.
Properties
static string SavePath [get]
Full path to the save file in Application.persistentDataPath.
static SaveData SaveData [get, private set]
The active save object used by the game.
Static Private Attributes
const string SaveFileName = "save.json"
File name of the save.
Detailed Description
Manages saving and loading of game data and exposes helpers to read and update the current save.
Definition at line 12 of file SaveSystemManager.cs.
Member Function Documentation
AdvanceLevel()
void Manager.SaveSystemManager.AdvanceLevel (int newSeed) inline static
Advances to the next level, updates the seed, and resets per-level fields.
Parameters
newSeed Seed for the next level.
Definition at line 79 of file SaveSystemManager.cs.
References Saving.SaveData.BossCleared, Saving.SaveData.BossRoomOpen, Saving.SaveData.CameraForward, Saving.SaveData.CurrentRoomID, Saving.SaveData.DestroyableWallsActive, Saving.SaveData.DestroyableWallsHealth, Saving.SaveData.DigitMiniGameCleared, Saving.SaveData.GlyphMiniGameCleared, Saving.SaveData.Items, Saving.SaveData.Level, Saving.SaveData.PlayerForward, Saving.SaveData.PlayerPosition, SaveData, Saving.SaveData.Seed, and Saving.SaveData.VisitedRooms.
Referenced by Interaction.LevelExitInteraction.Interact().
GetBossCleared()
bool Manager.SaveSystemManager.GetBossCleared () static
Gets whether the boss fight is cleared.
References SaveData.
Referenced by Spawning.BossSpawnerVoronoi.BossSpawnerVoronoi().
GetBossRoomOpen()
bool Manager.SaveSystemManager.GetBossRoomOpen () static
Gets whether the boss room door is open.
References SaveData.
Referenced by Manager.GameManagerVoronoi.RestoreBossDoorState().
GetCamRotation()
Vector3 Manager.SaveSystemManager.GetCamRotation () static
Gets the saved camera forward direction.
References SaveData.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
GetCurrentRoomID()
int Manager.SaveSystemManager.GetCurrentRoomID () static
Gets the current room id.
References SaveData.
Referenced by Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom().
GetDestroyableWallHealth()
int Manager.SaveSystemManager.GetDestroyableWallHealth (int idx) inline static
Gets the health for a destroyable wall by index, or 0 if out of range.
Definition at line 226 of file SaveSystemManager.cs.
References GetDestroyableWallsHealth().
Referenced by Interaction.DestroyableWallInteraction.InitializeFromSave().
GetDestroyableWallsActive()
List< bool > Manager.SaveSystemManager.GetDestroyableWallsActive () inline static
Gets the active flags list for destroyable walls (creates if null).
Definition at line 184 of file SaveSystemManager.cs.
References Saving.SaveData.DestroyableWallsActive, and SaveData.
Referenced by Dungeon.VoronoiGenerator.CreateWall(), and SetDestroyableWallActive().
GetDestroyableWallsHealth()
List< int > Manager.SaveSystemManager.GetDestroyableWallsHealth () inline static
Gets the health list for destroyable walls (creates if null).
Definition at line 206 of file SaveSystemManager.cs.
References Saving.SaveData.DestroyableWallsHealth, and SaveData.
Referenced by Dungeon.VoronoiGenerator.CreateWall(), GetDestroyableWallHealth(), and SetDestroyableWallHealth().
GetEquipment()
ItemInstance[,] Manager.SaveSystemManager.GetEquipment () inline static
Returns a 3x2 grid view of the equipment from the 1D array, filtering out empty entries.
Definition at line 343 of file SaveSystemManager.cs.
References SaveData.
Referenced by Inventory.Inventory.Awake().
GetInventory()
ItemInstance[,] Manager.SaveSystemManager.GetInventory () inline static
Returns a 4x5 grid view of the inventory from the 1D array, filtering out empty entries.
Definition at line 318 of file SaveSystemManager.cs.
References SaveData.
Referenced by Inventory.Inventory.Awake().
GetLevel()
int Manager.SaveSystemManager.GetLevel () static
Gets the current level.
References SaveData.
Referenced by Enemy.EnemyLevelScaler.Apply(), and Dungeon.VoronoiGenerator.RandomizeSizeAndPoints().
GetPlayerPosition()
Vector3 Manager.SaveSystemManager.GetPlayerPosition () static
Gets the saved player position.
References SaveData.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
GetPlayerRotation()
Vector3 Manager.SaveSystemManager.GetPlayerRotation () static
Gets the saved player forward direction.
References SaveData.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
GetSeed()
int Manager.SaveSystemManager.GetSeed () static
Gets the current seed.
References SaveData.
Referenced by Manager.GameManagerVoronoi.GenerateDungeon(), Manager.GameManagerVoronoi.InitializeSpawners(), and Spawning.ItemSpawnerVoronoi.SpawnInRoom().
GetStats()
List< float > Manager.SaveSystemManager.GetStats () static
References SaveData.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
GetVisitedRooms()
List< bool > Manager.SaveSystemManager.GetVisitedRooms () static
Gets the visited flags list for all rooms.
References SaveData.
Referenced by Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom().
InitializeVisitedRooms()
void Manager.SaveSystemManager.InitializeVisitedRooms (int roomCount) static
Initializes the visited list with the given room count (all false).
Parameters
roomCount Number of rooms.
References Saving.SaveData.VisitedRooms.
Referenced by Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom().
IsCollectibleActive()
bool Manager.SaveSystemManager.IsCollectibleActive (int idx) inline static
Gets whether a collectible at index is active. Grows the list if needed.
Definition at line 288 of file SaveSystemManager.cs.
References Saving.SaveData.Items, and SaveData.
Referenced by Spawning.ItemSpawnerVoronoi.SpawnInRoom().
Load()
void Manager.SaveSystemManager.Load () inline static
Loads save data from disk if it exists; otherwise keeps SaveData null and logs a message.
Definition at line 42 of file SaveSystemManager.cs.
References SaveData, and SavePath.
Referenced by Manager.ButtonManager.LoadGame().
Save()
void Manager.SaveSystemManager.Save () inline static
Serializes SaveData to JSON and writes it to disk.
Definition at line 32 of file SaveSystemManager.cs.
References SaveData, and SavePath.
Referenced by Manager.ButtonManager.SaveGame(), and StartNewRun().
SetBossCleared()
void Manager.SaveSystemManager.SetBossCleared (bool cleared) static
Sets whether the boss fight is cleared.
References Saving.SaveData.BossCleared.
Referenced by Spawning.BossSpawnerVoronoi.OnBossEnemyDied().
SetBossRoomOpen()
void Manager.SaveSystemManager.SetBossRoomOpen (bool open) static
Sets whether the boss room door is open.
References Saving.SaveData.BossRoomOpen.
Referenced by Spawning.BossSpawnerVoronoi.OnBossEnemyDied(), and Manager.GameManagerVoronoi.OnBossKeyUsed().
SetCamRotation()
void Manager.SaveSystemManager.SetCamRotation (Vector3 direct) static
Sets the saved camera forward direction.
References Saving.SaveData.CameraForward.
Referenced by Manager.ButtonManager.SaveGame(), and Manager.GameManagerVoronoi.SpawnPlayer().
SetCollectibleActive()
void Manager.SaveSystemManager.SetCollectibleActive (int idx, bool active) inline static
Sets whether a collectible at index is active. Grows the list if needed.
Definition at line 302 of file SaveSystemManager.cs.
References Saving.SaveData.Items, and SaveData.
Referenced by Items.CollectibleItem.Interact().
SetCurrentRoomID()
void Manager.SaveSystemManager.SetCurrentRoomID (int id) static
Sets the current room id.
References Saving.SaveData.CurrentRoomID.
Referenced by Manager.GameManagerVoronoi.OnRoomEntered(), and Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom().
SetDestroyableWallActive()
void Manager.SaveSystemManager.SetDestroyableWallActive (int idx, bool active) inline static
Sets the active flag for a destroyable wall by index (safe bounds check).
Definition at line 194 of file SaveSystemManager.cs.
References GetDestroyableWallsActive().
Referenced by Interaction.DestroyableWallInteraction.Interact().
SetDestroyableWallHealth()
void Manager.SaveSystemManager.SetDestroyableWallHealth (int idx, int hp) inline static
Sets the health value for a destroyable wall by index (safe bounds check).
Definition at line 216 of file SaveSystemManager.cs.
References GetDestroyableWallsHealth().
Referenced by Interaction.DestroyableWallInteraction.Interact().
SetEquipment()
void Manager.SaveSystemManager.SetEquipment (ItemInstance grid[,]) inline static
Writes a 3x2 equipment grid back to the 1D save array.
Definition at line 358 of file SaveSystemManager.cs.
References SaveData.
Referenced by Interaction.LevelExitInteraction.Interact(), and Manager.ButtonManager.SaveGame().
SetInventory()
void Manager.SaveSystemManager.SetInventory (ItemInstance grid[,]) inline static
Writes a 4x5 inventory grid back to the 1D save array.
Definition at line 333 of file SaveSystemManager.cs.
References SaveData.
Referenced by Interaction.LevelExitInteraction.Interact(), and Manager.ButtonManager.SaveGame().
SetPlayerPosition()
void Manager.SaveSystemManager.SetPlayerPosition (Vector3 pos) static
Sets the saved player position.
References Saving.SaveData.PlayerPosition.
Referenced by Manager.ButtonManager.SaveGame(), and Manager.GameManagerVoronoi.SpawnPlayer().
SetPlayerRotation()
void Manager.SaveSystemManager.SetPlayerRotation (Vector3 direct) static
Sets the saved player forward direction.
References Saving.SaveData.PlayerForward.
Referenced by Manager.ButtonManager.SaveGame(), and Manager.GameManagerVoronoi.SpawnPlayer().
SetRoomVisited()
void Manager.SaveSystemManager.SetRoomVisited (int roomId, bool visited) inline static
Sets the visited state for a room id (safe bounds check).
Definition at line 169 of file SaveSystemManager.cs.
References SaveData.
Referenced by Manager.GameManagerVoronoi.OnRoomEntered(), and Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom().
SetStats()
void Manager.SaveSystemManager.SetStats (List< float > currStats, List< float > maxStats) inline static
Sets current and max stats lists.
Definition at line 277 of file SaveSystemManager.cs.
References Saving.SaveData.CurrentStats, and Saving.SaveData.MaxStats.
Referenced by Interaction.LevelExitInteraction.Interact(), and Manager.ButtonManager.SaveGame().
StartNewRun()
void Manager.SaveSystemManager.StartNewRun (int newSeed) inline static
Creates a fresh save for a new run and writes it immediately.
Parameters
newSeed Seed to use for generation.
Definition at line 60 of file SaveSystemManager.cs.
References Save(), and SaveData.
Referenced by Manager.ButtonManager.StartGame().
Member Data Documentation
List< float >
Manager.SaveSystemManager.List< float > static
Gets current and max stats lists.
Returns
Tuple of (currentStats, maxStats).
Definition at line 272 of file SaveSystemManager.cs.
SaveFileName
const string Manager.SaveSystemManager.SaveFileName = "save.json" static private
File name of the save.
Definition at line 17 of file SaveSystemManager.cs.
Property Documentation
SaveData
SaveData Manager.SaveSystemManager.SaveData static get private set
The active save object used by the game.
Definition at line 27 of file SaveSystemManager.cs.
Referenced by AdvanceLevel(), GetBossCleared(), GetBossRoomOpen(), GetCamRotation(), GetCurrentRoomID(), GetDestroyableWallsActive(), GetDestroyableWallsHealth(), GetEquipment(), GetInventory(), GetLevel(), GetPlayerPosition(), GetPlayerRotation(), GetSeed(), GetStats(), GetVisitedRooms(), IsCollectibleActive(), Load(), Manager.ButtonManager.LoadGame(), Save(), SetCollectibleActive(), SetEquipment(), SetInventory(), SetRoomVisited(), StartNewRun(), MiniGame.CanvasDraw.Update(), MiniGame.CanvasDraw.ValidDigit(), and MiniGame.CanvasDraw.ValidGlyph().
SavePath
string Manager.SaveSystemManager.SavePath static get private
Full path to the save file in Application.persistentDataPath.
Definition at line 22 of file SaveSystemManager.cs.
Referenced by Load(), and Save().
The documentation for this class was generated from the following file:
SaveSystemManager.cs