artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/ac2133cb9eb94135901b82c08284e509/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ac2133cb9eb94135901b82c08284e509
run_name: painted-mule-129
run_uuid: ac2133cb9eb94135901b82c08284e509
source_name: ''
source_type: 4
source_version: ''
start_time: 1749147487169
status: 1
tags: []
user_id: arman
