artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/2b54556949c2449ab90dc7430ad798a2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2b54556949c2449ab90dc7430ad798a2
run_name: efficient-kite-499
run_uuid: 2b54556949c2449ab90dc7430ad798a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1753519774844
status: 1
tags: []
user_id: arman
