artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/a90891ee3bcc49a2b4d7050fc0b52811/artifacts
deleted_time: 1749147522503
end_time: 1749146744835
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
run_id: a90891ee3bcc49a2b4d7050fc0b52811
run_name: vaunted-auk-974
run_uuid: a90891ee3bcc49a2b4d7050fc0b52811
source_name: ''
source_type: 4
source_version: ''
start_time: 1749146544479
status: 4
tags: []
user_id: arman
