artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/39a21357dae24d6a802de173f47f033f/artifacts
end_time: 1749147486120
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 39a21357dae24d6a802de173f47f033f
run_name: stylish-sloth-912
run_uuid: 39a21357dae24d6a802de173f47f033f
source_name: ''
source_type: 4
source_version: ''
start_time: 1749147398387
status: 3
tags: []
user_id: arman
