artifact_uri: /home/arman/Documents/arman/Uni/Master/Semester 3/project/mlrun/0/bf9e7b4be09046d5a34130e61db2a006/artifacts
end_time: 1753519769567
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bf9e7b4be09046d5a34130e61db2a006
run_name: defiant-fawn-553
run_uuid: bf9e7b4be09046d5a34130e61db2a006
source_name: ''
source_type: 4
source_version: ''
start_time: 1753519723393
status: 3
tags: []
user_id: arman
