Projektarbeit 24/25: Enemy.EnemyLevelScaler Class Reference
Enemy.EnemyLevelScaler Class Reference
Applies per-level scaling to enemies/bosses at spawn time. Level 1 = base prefab values, from Level 2 upwards add fixed increments.
Static Public Member Functions
static void Apply (Stats.Stats s, bool isBoss=false)
Applies deterministic stat scaling to an enemy or boss based on the current game level.
Static Private Member Functions
static void EnsureMinSlots (Stats.Stats s, int minCount)
Ensures that the Stats object has at least the required number of stat slots in both its maximum and current stat lists, preventing index errors.
Static Private Attributes
const float EnemyHpPerLevel = 20f
Additional health granted per level (starting from level 2) for regular enemies.
const float EnemyDmgPerLevel = 1f
Additional damage granted per level (starting from level 2) for regular enemies.
const float BossHpPerLevel = 100f
Additional health granted per level (starting from level 2) for bosses.
const float BossDmgPerLevel = 2f
Additional damage granted per level (starting from level 2) for bosses.
Detailed Description
Applies per-level scaling to enemies/bosses at spawn time. Level 1 = base prefab values, from Level 2 upwards add fixed increments.
Definition at line 12 of file EnemyLevelScaler.cs.
Member Function Documentation
Apply()
void Enemy.EnemyLevelScaler.Apply (Stats.Stats s, bool isBoss = false) inline static
Applies deterministic stat scaling to an enemy or boss based on the current game level.
Parameters
s The Stats object of the enemy or boss.
isBoss If true, applies boss-level increments; otherwise, enemy increments.
Definition at line 53 of file EnemyLevelScaler.cs.
References BossDmgPerLevel, BossHpPerLevel, EnemyDmgPerLevel, EnemyHpPerLevel, EnsureMinSlots(), and Manager.SaveSystemManager.GetLevel().
Referenced by Spawning.BossSpawnerVoronoi.BossSpawnerVoronoi(), and Spawning.EnemySpawnerVoronoi.EnemySpawnerVoronoi().
EnsureMinSlots()
void Enemy.EnemyLevelScaler.EnsureMinSlots (Stats.Stats s, int minCount) inline static private
Ensures that the Stats object has at least the required number of stat slots in both its maximum and current stat lists, preventing index errors.
Parameters
s The Stats object to expand if needed.
minCount Minimum number of stat slots required.
Definition at line 40 of file EnemyLevelScaler.cs.
Referenced by Apply().
Member Data Documentation
BossDmgPerLevel
const float Enemy.EnemyLevelScaler.BossDmgPerLevel = 2f static private
Additional damage granted per level (starting from level 2) for bosses.
Definition at line 32 of file EnemyLevelScaler.cs.
Referenced by Apply().
BossHpPerLevel
const float Enemy.EnemyLevelScaler.BossHpPerLevel = 100f static private
Additional health granted per level (starting from level 2) for bosses.
Definition at line 27 of file EnemyLevelScaler.cs.
Referenced by Apply().
EnemyDmgPerLevel
const float Enemy.EnemyLevelScaler.EnemyDmgPerLevel = 1f static private
Additional damage granted per level (starting from level 2) for regular enemies.
Definition at line 22 of file EnemyLevelScaler.cs.
Referenced by Apply().
EnemyHpPerLevel
const float Enemy.EnemyLevelScaler.EnemyHpPerLevel = 20f static private
Additional health granted per level (starting from level 2) for regular enemies.
Definition at line 17 of file EnemyLevelScaler.cs.
Referenced by Apply().
The documentation for this class was generated from the following file:
EnemyLevelScaler.cs