Projektarbeit 24/25: Manager.GameInputManager Class Reference
Manager.GameInputManager Class Reference
Manages player input for movement and camera control using the Input System. Handles input locking and cursor visibility for immersive gameplay.
Public Member Functions
Vector2 GetMovementVectorNormalized ()
Retrieves normalized movement input as a 2D vector.
Vector2 GetLookDelta ()
Retrieves the player's input for the camera-look direction.
void MouseLocked (bool locked)
Locks or unlocks the cursor based on the specified state.
Properties
static GameInputManager Instance [get, private set]
Singleton instance of the GameInputManager, ensuring there is only one instance in the scene. Provides global access to game input management functionality.
Private Member Functions
void Awake ()
Ensures there is only one instance of the GameInputManager in the scene. If another instance exists, it will be destroyed. Persists the instance across scenes for consistent game state management.
void OnDestroy ()
Ensures the cursor is unlocked and visible when the object is destroyed, typically when exiting the game.
Private Attributes
InputSystem_Actions _inputSystemActions
Instance of the input action map for handling player controls.
Detailed Description
Manages player input for movement and camera control using the Input System. Handles input locking and cursor visibility for immersive gameplay.
Definition at line 9 of file GameInputManager.cs.
Member Function Documentation
Awake()
void Manager.GameInputManager.Awake () inline private
Ensures there is only one instance of the GameInputManager in the scene. If another instance exists, it will be destroyed. Persists the instance across scenes for consistent game state management.
Initializes input actions and locks the cursor when the script awakens.
Definition at line 29 of file GameInputManager.cs.
References _inputSystemActions, Instance, and MouseLocked().
GetLookDelta()
Vector2 Manager.GameInputManager.GetLookDelta () inline
Retrieves the player's input for the camera-look direction.
Returns
A Vector2 representing the camera-look direction (x for horizontal rotation, y for vertical rotation).
Definition at line 68 of file GameInputManager.cs.
References _inputSystemActions.
GetMovementVectorNormalized()
Vector2 Manager.GameInputManager.GetMovementVectorNormalized () inline
Retrieves normalized movement input as a 2D vector.
Returns
A normalized Vector2 representing the player's movement direction (x for horizontal, y for vertical).
Definition at line 54 of file GameInputManager.cs.
References _inputSystemActions.
MouseLocked()
void Manager.GameInputManager.MouseLocked (bool locked) inline
Locks or unlocks the cursor based on the specified state.
Parameters
locked If true, the cursor is locked and hidden; if false, the cursor is unlocked and visible.
Definition at line 78 of file GameInputManager.cs.
Referenced by Awake(), Manager.UIManager.EnterCombatLock(), OnDestroy(), Manager.UIManager.ResumeGameplayIfNotGameOver(), Manager.CameraManager.SetCanvView(), Manager.CameraManager.SetFirstPersonView(), and Manager.UIManager.Update().
OnDestroy()
void Manager.GameInputManager.OnDestroy () inline private
Ensures the cursor is unlocked and visible when the object is destroyed, typically when exiting the game.
Definition at line 95 of file GameInputManager.cs.
References _inputSystemActions, Instance, and MouseLocked().
Member Data Documentation
_inputSystemActions
InputSystem_Actions Manager.GameInputManager._inputSystemActions private
Instance of the input action map for handling player controls.
Definition at line 20 of file GameInputManager.cs.
Referenced by Awake(), GetLookDelta(), GetMovementVectorNormalized(), and OnDestroy().
Property Documentation
Instance
GameInputManager Manager.GameInputManager.Instance static get private set
Singleton instance of the GameInputManager, ensuring there is only one instance in the scene. Provides global access to game input management functionality.
Definition at line 15 of file GameInputManager.cs.
Referenced by Awake(), Manager.UIManager.EnterCombatLock(), OnDestroy(), Manager.UIManager.ResumeGameplayIfNotGameOver(), Manager.CameraManager.SetCanvView(), Manager.CameraManager.SetFirstPersonView(), and Manager.UIManager.Update().
The documentation for this class was generated from the following file:
GameInputManager.cs