Projektarbeit 24/25: MiniGame.DrawingTrigger Class Reference
MiniGame.DrawingTrigger Class Reference
Handles player interaction with a drawing canvas. Displays instructions, activates the camera for drawing, and triggers the canvas view when the player presses the draw key. Implements the IInteractable interface.
Public Member Functions
void Interact (GameObject interactor)
Called when the player interacts with the object. Displays instructions and activates the canvas for drawing.
void OnExit (GameObject interactor)
Called when the player exits the interaction area. Hides any instruction panel related to drawing.
bool ShouldRepeat ()
Determines whether the interaction can be repeated.
Private Attributes
Transform center
The central point to focus the camera on when the canvas is active.
Detailed Description
Handles player interaction with a drawing canvas. Displays instructions, activates the camera for drawing, and triggers the canvas view when the player presses the draw key. Implements the IInteractable interface.
Definition at line 13 of file DrawingTrigger.cs.
Member Function Documentation
Interact()
void MiniGame.DrawingTrigger.Interact (GameObject interactor) inline
Called when the player interacts with the object. Displays instructions and activates the canvas for drawing.
Parameters
interactor The GameObject player interacting with this object.
Implements Interfaces.IInteractable.
Definition at line 26 of file DrawingTrigger.cs.
References Manager.CameraManager.ActiveCanvasDraw, center, Manager.CameraManager.Instance, Manager.EventManager.Instance, Manager.UIManager.Instance, Manager.CameraManager.SetActiveCanvas(), Manager.CameraManager.SetCanvasTarget(), Manager.UIManager.ShowPanel(), MiniGame.CanvasDraw.ToDraw, and Manager.EventManager.TriggerCanvasView().
OnExit()
void MiniGame.DrawingTrigger.OnExit (GameObject interactor) inline
Called when the player exits the interaction area. Hides any instruction panel related to drawing.
Parameters
interactor The GameObject player exiting the interaction.
Implements Interfaces.IInteractable.
Definition at line 57 of file DrawingTrigger.cs.
References Manager.UIManager.HidePanel(), and Manager.UIManager.Instance.
ShouldRepeat()
bool MiniGame.DrawingTrigger.ShouldRepeat () inline
Determines whether the interaction can be repeated.
Returns
Always returns true, allowing repeated interaction.
Implements Interfaces.IInteractable.
Definition at line 66 of file DrawingTrigger.cs.
Member Data Documentation
center
Transform MiniGame.DrawingTrigger.center private
The central point to focus the camera on when the canvas is active.
Definition at line 18 of file DrawingTrigger.cs.
Referenced by Interact().
The documentation for this class was generated from the following file:
DrawingTrigger.cs