Projektarbeit 24/25: Dungeon.VoronoiGenerator Class Reference
Dungeon.VoronoiGenerator Class Reference
Generates a procedural dungeon using Voronoi/Delaunay and builds the scene (floors, walls, doors, pillars). Also assigns room types and compute paths.
Public Member Functions
void GenerateDungeon (int seed)
Entry point to generate a new dungeon with the given seed.
DungeonGraph GetDungeonGraph ()
Returns the current dungeon graph instance.
Properties
float DungeonSize [get]
Public accessor for the current dungeon size.
int ForcedItemRoomId = -1 [get, private set]
ID of the chosen item room used for the forced path (-1 if none).
Private Member Functions
void GenerateDebugData ()
Generates data: points, triangles, Voronoi edges, and centers.
void RandomizeSizeAndPoints ()
Randomizes dungeon size and number of points based on the current level and seed.
void BuildAndPopulateGraph ()
Builds the dungeon graph and connects rooms with neighbors.
List< Room > BuildRoomGraph ()
Creates room instances from the generated points and seeds their incircle radius.
HashSet< int > GetNeighbors (int pointID, Room room)
Finds neighboring point indices that share a triangle with the given point.
void BuildDungeon ()
Builds the dungeon floor, scatters props, and creates outer walls.
void ScatterCategory (List< GameObject > prefabs, int count, int seedSalt)
Scatters a category of prefabs randomly inside the map borders.
void BuildVoronoi (List< Edge > voronoi)
Builds only the segmented Walls for the voronoi-edges.
void PlacePillars (List< Triangle > delaunay)
Places all Pillars at the intersection points of edges and at the corner points.
void CreateWall (Vector3 start, Vector3 end, int edgeId)
Create a wall using scaled wall segments, possibly placing a door or breakable wall.
void SetupBossDoor (GameObject doorObj, List< Room > roomsWithEdge)
Configures a door as a boss door by adding logic and visuals (fog wall, narrow door panel, correct rotation).
void CreateWallSegment (Vector3 start, Vector3 end, float scale)
Create a wall segment from the prefab and scale and rotate it between two points.
void AssignRoomTypes ()
Assigns room types such as Start, Boss, Item, Enemy, etc.
void ComputeForcedDoorPairs ()
Computes the door path that must be traversable (start → some item room), but avoids passing through the Boss room. Also stores the target item room id in _forcedItemRoomId.
void ComputeDebugShortestItemPath ()
Computes the shortest path from the start room to the first item room (debug only)
List< Point > GeneratePoints (int count, float radius, float dungeonSize)
Generates random points with a minimum spacing radius.
List< Triangle > BowyerWatson (List< Point > points)
Calculates the Delaunay-Triangulation with a set of given Points.
List< Edge > GenerateVoronoi (List< Triangle > triangulation)
This Method generates the Voronoi-Diagram by drawing the bisectors of every triangle, joining matching edges and extending the border ones.
bool PointOutTriangle (Point pt, Point v1, Point v2, Point v3)
Checks if a Point is outside a triangle.
float Sign (Point p1, Point p2, Point p3)
Computes the sign of the area for three points (used in triangle check)
Point FindIntersectionWithMapBoundary (Edge edge, float dungeonSize)
Finds the intersection point of an edge with the map boundary.
Point CheckPoints (List< Point > points, Point reference)
Find the closest Point from a list to another point.
void PruneNeighborsByEdgeLength ()
Removes neighbors connected by too short Voronoi edges.
bool HasTraversableEdge (Room a, Room b)
Checks if there is a traversable Voronoi edge between two rooms.
void PrintBossRoomDoorInfo ()
Logs detailed info about the boss room and its door edges.
void OnDrawGizmos ()
Draws various debug visualizations (points, triangles, labels, edges, etc.)
void DrawLine (Point a, Point b)
Draws a line between two points in Gizmos.
Static Private Member Functions
static string GetPairKey (int a, int b)
Returns a normalized key string for two room IDs.
Private Attributes
GameObject pillar
Pillar prefab placed at room intersections and map corners.
GameObject wall
Wall segment prefab for regular walls.
GameObject floorNormal
Tiled floor prefab (placed in a grid).
GameObject floorShader
Large floor prefab that uses a shader material.
GameObject floorWave
Large floor prefab with an animated wave shader.
GameObject door
Door prefab inserted into wall lines.
GameObject destroyableWall
Breakable wall prefab used instead of a door in some spots.
float size = 40
Side length of the square dungeon area.
int numPoints = 5
Number of seed points used to generate rooms.
float minDoorEdgeLength = 4f
Minimum-edge length required to allow a door.
Material[] skyboxMaterials
Skybox materials rotated based on the seed.
List< GameObject > grassSmallPrefabs
Small grass prefabs for scattering.
List< GameObject > grassBigPrefabs
Big grass prefabs for scattering.
List< GameObject > treePrefabs
Tree prefabs for scattering.
List< GameObject > rockPrefabs
Rock prefabs for scattering.
int grassSmallCount = 600
Number of small grass instances to spawn.
int grassBigCount = 80
Number of big grass instances to spawn.
int treeCount = 40
Number of trees to spawn.
int rockCount = 80
Number of rocks to spawn.
float spawnMargin = 1f
Margin from the outer walls used when scattering props.
float spawnY
Y position for scattered props.
DungeonGraph _dungeonGraph
The generated dungeon graph (rooms, doors, walls).
System.Random _rng
Random generator scoped to this run.
int _seed
Current generation seed.
readonly HashSet< string > _forcedDoorPairs = new()
Set of normalized "roomA_roomB" keys that must have a door.
Light _light = new()
Reference to the main directional light (for stylistic changes).
int _breakableWallCounter
Running counter used to index breakable walls in the save.
bool showPoints = true
Show generated points in the scene view.
bool showCenters = true
Show circumcenters used by Voronoi.
bool showTriangles = true
Show Delaunay triangles.
bool showShortestItemPath = true
Show the computed shortest path to an item room.
bool showDoorEdgeID = true
Show edge IDs and placed door IDs.
bool showVoronoi = true
Show Voronoi edges.
bool showBisectors = true
Show triangle bisectors.
bool showVoronoiIntersections = true
Show intersection points with the map boundary.
bool showSuperTriangle = true
Show the super triangle used during triangulation.
List< Point > _debugPoints
Random points used for generation.
List< Triangle > _debugTriangles
Delaunay triangles.
List< Point > _debugShortestItemPath
Path centers for the item path.
List< Edge > _debugVoronoi
Voronoi edges.
List< Point > _debugCenters
Circumcenters inside the map.
List< Edge > _debugBisectors
Raw bisectors drawn per triangle.
List< Point > _debugVoronoiIntersections
Intersections of rays with the boundary.
Triangle _debugSuperTriangle
Super triangle.
Static Private Attributes
const double DoorProbability = 0.5
Base probability to place a door on eligible edges.
Detailed Description
Generates a procedural dungeon using Voronoi/Delaunay and builds the scene (floors, walls, doors, pillars). Also assigns room types and compute paths.
Definition at line 16 of file VoronoiGenerator.cs.
Member Function Documentation
AssignRoomTypes()
void Dungeon.VoronoiGenerator.AssignRoomTypes () inline private
Assigns room types such as Start, Boss, Item, Enemy, etc.
Definition at line 755 of file VoronoiGenerator.cs.
References _dungeonGraph, and _rng.
Referenced by GenerateDungeon().
BowyerWatson()
List< Triangle > Dungeon.VoronoiGenerator.BowyerWatson (List< Point > points) inline private
Calculates the Delaunay-Triangulation with a set of given Points.
Parameters
points The set of points used to calculate the delaunay triangulation
Returns
The Delaunay-Triangulation as a set of Triangles
Definition at line 929 of file VoronoiGenerator.cs.
References _debugSuperTriangle, Dungeon.Edge.Equals(), and size.
Referenced by GenerateDebugData().
BuildAndPopulateGraph()
void Dungeon.VoronoiGenerator.BuildAndPopulateGraph () inline private
Builds the dungeon graph and connects rooms with neighbors.
Definition at line 345 of file VoronoiGenerator.cs.
References _dungeonGraph, BuildRoomGraph(), and GetNeighbors().
Referenced by GenerateDungeon().
BuildDungeon()
void Dungeon.VoronoiGenerator.BuildDungeon () inline private
Builds the dungeon floor, scatters props, and creates outer walls.
Definition at line 417 of file VoronoiGenerator.cs.
References _seed, CreateWall(), floorNormal, floorShader, floorWave, grassBigCount, grassBigPrefabs, grassSmallCount, grassSmallPrefabs, rockCount, rockPrefabs, ScatterCategory(), size, skyboxMaterials, treeCount, and treePrefabs.
Referenced by GenerateDungeon().
BuildRoomGraph()
List< Room > Dungeon.VoronoiGenerator.BuildRoomGraph () inline private
Creates room instances from the generated points and seeds their incircle radius.
Definition at line 359 of file VoronoiGenerator.cs.
References _debugPoints, _dungeonGraph, Dungeon.Point.GetDistance(), and size.
Referenced by BuildAndPopulateGraph().
BuildVoronoi()
void Dungeon.VoronoiGenerator.BuildVoronoi (List< Edge > voronoi) inline private
Builds only the segmented Walls for the voronoi-edges.
Parameters
voronoi The list of voronoi edges
Definition at line 530 of file VoronoiGenerator.cs.
References _dungeonGraph, Dungeon.Edge.A, Dungeon.Edge.B, CreateWall(), Dungeon.Edge.Id, Dungeon.Edge.Room1, Dungeon.Edge.Room2, Dungeon.Point.X, and Dungeon.Point.Y.
Referenced by GenerateDungeon().
CheckPoints()
Point Dungeon.VoronoiGenerator.CheckPoints (List< Point > points, Point reference) inline private
Find the closest Point from a list to another point.
Parameters
points The list of points we want to get the closest from
reference The point we want to get closest to
Returns
the point from the list that is closest to reference
Definition at line 1205 of file VoronoiGenerator.cs.
Referenced by FindIntersectionWithMapBoundary().
ComputeDebugShortestItemPath()
void Dungeon.VoronoiGenerator.ComputeDebugShortestItemPath () inline private
Computes the shortest path from the start room to the first item room (debug only)
Definition at line 860 of file VoronoiGenerator.cs.
References _debugShortestItemPath, _dungeonGraph, and ForcedItemRoomId.
Referenced by GenerateDungeon().
ComputeForcedDoorPairs()
void Dungeon.VoronoiGenerator.ComputeForcedDoorPairs () inline private
Computes the door path that must be traversable (start → some item room), but avoids passing through the Boss room. Also stores the target item room id in _forcedItemRoomId.
Definition at line 806 of file VoronoiGenerator.cs.
References _dungeonGraph, _forcedDoorPairs, ForcedItemRoomId, and GetPairKey().
Referenced by GenerateDungeon().
CreateWall()
void Dungeon.VoronoiGenerator.CreateWall (Vector3 start, Vector3 end, int edgeId) inline private
Create a wall using scaled wall segments, possibly placing a door or breakable wall.
Parameters
start Start of the wall edge
end End of the wall edge
edgeId Unique identifier for this wall edge
Definition at line 573 of file VoronoiGenerator.cs.
References _breakableWallCounter, _dungeonGraph, _forcedDoorPairs, _rng, CreateWallSegment(), destroyableWall, door, DoorProbability, Manager.SaveSystemManager.GetDestroyableWallsActive(), Manager.SaveSystemManager.GetDestroyableWallsHealth(), GetPairKey(), minDoorEdgeLength, SetupBossDoor(), and size.
Referenced by BuildDungeon(), and BuildVoronoi().
CreateWallSegment()
void Dungeon.VoronoiGenerator.CreateWallSegment (Vector3 start, Vector3 end, float scale) inline private
Create a wall segment from the prefab and scale and rotate it between two points.
Parameters
start The beginning of the wall
end The end of the wall
scale Local X scale of the segment.
Definition at line 736 of file VoronoiGenerator.cs.
References wall.
Referenced by CreateWall().
DrawLine()
void Dungeon.VoronoiGenerator.DrawLine (Point a, Point b) inline private
Draws a line between two points in Gizmos.
Parameters
a Point A
b Point B
Definition at line 1441 of file VoronoiGenerator.cs.
References Dungeon.Point.X, and Dungeon.Point.Y.
Referenced by OnDrawGizmos().
FindIntersectionWithMapBoundary()
Point Dungeon.VoronoiGenerator.FindIntersectionWithMapBoundary (Edge edge, float dungeonSize) inline private
Finds the intersection point of an edge with the map boundary.
Parameters
edge The edge
dungeonSize The dungeon size
Returns
The intersection Point
Definition at line 1162 of file VoronoiGenerator.cs.
References Dungeon.Edge.A, Dungeon.Edge.B, CheckPoints(), Dungeon.Point.X, and Dungeon.Point.Y.
Referenced by GenerateVoronoi().
GenerateDebugData()
void Dungeon.VoronoiGenerator.GenerateDebugData () inline private
Generates data: points, triangles, Voronoi edges, and centers.
Definition at line 295 of file VoronoiGenerator.cs.
References _debugCenters, _debugPoints, _debugTriangles, _debugVoronoi, BowyerWatson(), GeneratePoints(), GenerateVoronoi(), numPoints, and size.
Referenced by GenerateDungeon().
GenerateDungeon()
void Dungeon.VoronoiGenerator.GenerateDungeon (int seed) inline
Entry point to generate a new dungeon with the given seed.
Parameters
seed Seed for random generation.
Definition at line 266 of file VoronoiGenerator.cs.
References _breakableWallCounter, _debugTriangles, _debugVoronoi, _light, _rng, _seed, AssignRoomTypes(), BuildAndPopulateGraph(), BuildDungeon(), BuildVoronoi(), ComputeDebugShortestItemPath(), ComputeForcedDoorPairs(), GenerateDebugData(), PlacePillars(), PruneNeighborsByEdgeLength(), and RandomizeSizeAndPoints().
GeneratePoints()
List< Point > Dungeon.VoronoiGenerator.GeneratePoints (int count, float radius, float dungeonSize) inline private
Generates random points with a minimum spacing radius.
Parameters
count Number of points to generate.
radius Minimum distance between points.
dungeonSize Area limit (0…size for X and Y).
Returns
List of generated points.
Definition at line 891 of file VoronoiGenerator.cs.
References _rng, and Dungeon.Point.GetDistance().
Referenced by GenerateDebugData().
GenerateVoronoi()
List< Edge > Dungeon.VoronoiGenerator.GenerateVoronoi (List< Triangle > triangulation) inline private
This Method generates the Voronoi-Diagram by drawing the bisectors of every triangle, joining matching edges and extending the border ones.
Parameters
triangulation A valid Delaunay-Triangulation
Returns
The List of Voronoi Edges
Definition at line 1011 of file VoronoiGenerator.cs.
References _debugBisectors, _debugVoronoiIntersections, Dungeon.Edge.A, Dungeon.Edge.B, Dungeon.Point.Equals(), FindIntersectionWithMapBoundary(), PointOutTriangle(), Dungeon.Edge.Room1, Dungeon.Edge.Room2, size, Dungeon.Point.X, and Dungeon.Point.Y.
Referenced by GenerateDebugData().
GetDungeonGraph()
DungeonGraph Dungeon.VoronoiGenerator.GetDungeonGraph () inline
Returns the current dungeon graph instance.
Definition at line 335 of file VoronoiGenerator.cs.
References _dungeonGraph.
GetNeighbors()
HashSet< int > Dungeon.VoronoiGenerator.GetNeighbors (int pointID, Room room) inline private
Finds neighboring point indices that share a triangle with the given point.
Parameters
pointID Index of the target point in _debugPoints
room Room for which neighbors are evaluated (unused, kept for context).
Returns
A HashSet of indices representing all neighboring points
Definition at line 385 of file VoronoiGenerator.cs.
References _debugPoints, _debugTriangles, and Dungeon.Point.Equals().
Referenced by BuildAndPopulateGraph().
GetPairKey()
string Dungeon.VoronoiGenerator.GetPairKey (int a, int b) static private
Returns a normalized key string for two room IDs.
Referenced by ComputeForcedDoorPairs(), and CreateWall().
HasTraversableEdge()
bool Dungeon.VoronoiGenerator.HasTraversableEdge (Room a, Room b) inline private
Checks if there is a traversable Voronoi edge between two rooms.
Parameters
a Room A
b Room B
Returns
True if there is a Voronoi edge between rooms that is at least the door length.
Definition at line 1242 of file VoronoiGenerator.cs.
References _debugVoronoi, Dungeon.Edge.A, Dungeon.Edge.B, Dungeon.Point.Equals(), Dungeon.Point.GetDistance(), minDoorEdgeLength, Dungeon.Edge.Room1, and Dungeon.Edge.Room2.
Referenced by PruneNeighborsByEdgeLength().
OnDrawGizmos()
void Dungeon.VoronoiGenerator.OnDrawGizmos () inline private
Draws various debug visualizations (points, triangles, labels, edges, etc.)
Definition at line 1293 of file VoronoiGenerator.cs.
References _debugBisectors, _debugCenters, _debugPoints, _debugShortestItemPath, _debugSuperTriangle, _debugTriangles, _debugVoronoi, _debugVoronoiIntersections, _dungeonGraph, DrawLine(), showBisectors, showCenters, showDoorEdgeID, showPoints, showShortestItemPath, showSuperTriangle, showTriangles, showVoronoi, and showVoronoiIntersections.
PlacePillars()
void Dungeon.VoronoiGenerator.PlacePillars (List< Triangle > delaunay) inline private
Places all Pillars at the intersection points of edges and at the corner points.
Parameters
delaunay The delaunay triangulation to get the circle centers
Definition at line 548 of file VoronoiGenerator.cs.
References pillar, and size.
Referenced by GenerateDungeon().
PointOutTriangle()
bool Dungeon.VoronoiGenerator.PointOutTriangle (Point pt, Point v1, Point v2, Point v3) inline private
Checks if a Point is outside a triangle.
Parameters
pt The point we want to know
v1 Point A
v2 Point B
v3 Point C
Returns
Weather the point is outside(true) or inside (false)
Definition at line 1132 of file VoronoiGenerator.cs.
References Sign().
Referenced by GenerateVoronoi().
PrintBossRoomDoorInfo()
void Dungeon.VoronoiGenerator.PrintBossRoomDoorInfo () inline private
Logs detailed info about the boss room and its door edges.
Definition at line 1262 of file VoronoiGenerator.cs.
References _dungeonGraph.
PruneNeighborsByEdgeLength()
void Dungeon.VoronoiGenerator.PruneNeighborsByEdgeLength () inline private
Removes neighbors connected by too short Voronoi edges.
Definition at line 1228 of file VoronoiGenerator.cs.
References _dungeonGraph, and HasTraversableEdge().
Referenced by GenerateDungeon().
RandomizeSizeAndPoints()
void Dungeon.VoronoiGenerator.RandomizeSizeAndPoints () inline private
Randomizes dungeon size and number of points based on the current level and seed.
Definition at line 309 of file VoronoiGenerator.cs.
References _seed, Manager.SaveSystemManager.GetLevel(), numPoints, and size.
Referenced by GenerateDungeon().
ScatterCategory()
void Dungeon.VoronoiGenerator.ScatterCategory (List< GameObject > prefabs, int count, int seedSalt) inline private
Scatters a category of prefabs randomly inside the map borders.
Parameters
prefabs Prefabs to choose from.
count How many instances to spawn.
seedSalt Salt added to the seed for independent randomness.
Definition at line 504 of file VoronoiGenerator.cs.
References _seed, size, spawnMargin, and spawnY.
Referenced by BuildDungeon().
SetupBossDoor()
void Dungeon.VoronoiGenerator.SetupBossDoor (GameObject doorObj, List< Room > roomsWithEdge) inline private
Configures a door as a boss door by adding logic and visuals (fog wall, narrow door panel, correct rotation).
Parameters
doorObj The door GameObject to configure.
roomsWithEdge The two connected rooms (one must be the boss room).
Definition at line 683 of file VoronoiGenerator.cs.
Referenced by CreateWall().
Sign()
float Dungeon.VoronoiGenerator.Sign (Point p1, Point p2, Point p3) inline private
Computes the sign of the area for three points (used in triangle check)
Parameters
p1 Point A
p2 Point B
p3 Point C
Returns
The sign of the area
Definition at line 1151 of file VoronoiGenerator.cs.
References Dungeon.Point.X, and Dungeon.Point.Y.
Referenced by PointOutTriangle().
Member Data Documentation
_breakableWallCounter
int Dungeon.VoronoiGenerator._breakableWallCounter private
Running counter used to index breakable walls in the save.
Definition at line 169 of file VoronoiGenerator.cs.
Referenced by CreateWall(), and GenerateDungeon().
_debugBisectors
List<Edge> Dungeon.VoronoiGenerator._debugBisectors private
Raw bisectors drawn per triangle.
Definition at line 248 of file VoronoiGenerator.cs.
Referenced by GenerateVoronoi(), and OnDrawGizmos().
_debugCenters
List<Point> Dungeon.VoronoiGenerator._debugCenters private
Circumcenters inside the map.
Definition at line 243 of file VoronoiGenerator.cs.
Referenced by GenerateDebugData(), and OnDrawGizmos().
_debugPoints
List<Point> Dungeon.VoronoiGenerator._debugPoints private
Random points used for generation.
Definition at line 223 of file VoronoiGenerator.cs.
Referenced by BuildRoomGraph(), GenerateDebugData(), GetNeighbors(), and OnDrawGizmos().
_debugShortestItemPath
List<Point> Dungeon.VoronoiGenerator._debugShortestItemPath private
Path centers for the item path.
Definition at line 233 of file VoronoiGenerator.cs.
Referenced by ComputeDebugShortestItemPath(), and OnDrawGizmos().
_debugSuperTriangle
Triangle Dungeon.VoronoiGenerator._debugSuperTriangle private
Super triangle.
Definition at line 258 of file VoronoiGenerator.cs.
Referenced by BowyerWatson(), and OnDrawGizmos().
_debugTriangles
List<Triangle> Dungeon.VoronoiGenerator._debugTriangles private
Delaunay triangles.
Definition at line 228 of file VoronoiGenerator.cs.
Referenced by GenerateDebugData(), GenerateDungeon(), GetNeighbors(), and OnDrawGizmos().
_debugVoronoi
List<Edge> Dungeon.VoronoiGenerator._debugVoronoi private
Voronoi edges.
Definition at line 238 of file VoronoiGenerator.cs.
Referenced by GenerateDebugData(), GenerateDungeon(), HasTraversableEdge(), and OnDrawGizmos().
_debugVoronoiIntersections
List<Point> Dungeon.VoronoiGenerator._debugVoronoiIntersections private
Intersections of rays with the boundary.
Definition at line 253 of file VoronoiGenerator.cs.
Referenced by GenerateVoronoi(), and OnDrawGizmos().
_dungeonGraph
DungeonGraph Dungeon.VoronoiGenerator._dungeonGraph private
The generated dungeon graph (rooms, doors, walls).
Definition at line 139 of file VoronoiGenerator.cs.
Referenced by AssignRoomTypes(), BuildAndPopulateGraph(), BuildRoomGraph(), BuildVoronoi(), ComputeDebugShortestItemPath(), ComputeForcedDoorPairs(), CreateWall(), GetDungeonGraph(), OnDrawGizmos(), PrintBossRoomDoorInfo(), and PruneNeighborsByEdgeLength().
_forcedDoorPairs
readonly HashSet<string> Dungeon.VoronoiGenerator._forcedDoorPairs = new() private
Set of normalized "roomA_roomB" keys that must have a door.
Definition at line 154 of file VoronoiGenerator.cs.
Referenced by ComputeForcedDoorPairs(), and CreateWall().
_light
Light Dungeon.VoronoiGenerator._light = new() private
Reference to the main directional light (for stylistic changes).
Definition at line 164 of file VoronoiGenerator.cs.
Referenced by GenerateDungeon().
_rng
System.Random Dungeon.VoronoiGenerator._rng private
Random generator scoped to this run.
Definition at line 144 of file VoronoiGenerator.cs.
Referenced by AssignRoomTypes(), CreateWall(), GenerateDungeon(), and GeneratePoints().
_seed
int Dungeon.VoronoiGenerator._seed private
Current generation seed.
Definition at line 149 of file VoronoiGenerator.cs.
Referenced by BuildDungeon(), GenerateDungeon(), RandomizeSizeAndPoints(), and ScatterCategory().
destroyableWall
GameObject Dungeon.VoronoiGenerator.destroyableWall private
Breakable wall prefab used instead of a door in some spots.
Definition at line 52 of file VoronoiGenerator.cs.
Referenced by CreateWall().
door
GameObject Dungeon.VoronoiGenerator.door private
Door prefab inserted into wall lines.
Definition at line 47 of file VoronoiGenerator.cs.
Referenced by CreateWall().
DoorProbability
const double Dungeon.VoronoiGenerator.DoorProbability = 0.5 static private
Base probability to place a door on eligible edges.
Definition at line 159 of file VoronoiGenerator.cs.
Referenced by CreateWall().
floorNormal
GameObject Dungeon.VoronoiGenerator.floorNormal private
Tiled floor prefab (placed in a grid).
Definition at line 32 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
floorShader
GameObject Dungeon.VoronoiGenerator.floorShader private
Large floor prefab that uses a shader material.
Definition at line 37 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
floorWave
GameObject Dungeon.VoronoiGenerator.floorWave private
Large floor prefab with an animated wave shader.
Definition at line 42 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
grassBigCount
int Dungeon.VoronoiGenerator.grassBigCount = 80 private
Number of big grass instances to spawn.
Definition at line 104 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
grassBigPrefabs
List<GameObject> Dungeon.VoronoiGenerator.grassBigPrefabs private
Big grass prefabs for scattering.
Definition at line 84 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
grassSmallCount
int Dungeon.VoronoiGenerator.grassSmallCount = 600 private
Number of small grass instances to spawn.
Definition at line 99 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
grassSmallPrefabs
List<GameObject> Dungeon.VoronoiGenerator.grassSmallPrefabs private
Small grass prefabs for scattering.
Definition at line 79 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
minDoorEdgeLength
float Dungeon.VoronoiGenerator.minDoorEdgeLength = 4f private
Minimum-edge length required to allow a door.
Definition at line 68 of file VoronoiGenerator.cs.
Referenced by CreateWall(), and HasTraversableEdge().
numPoints
int Dungeon.VoronoiGenerator.numPoints = 5 private
Number of seed points used to generate rooms.
Definition at line 63 of file VoronoiGenerator.cs.
Referenced by GenerateDebugData(), and RandomizeSizeAndPoints().
pillar
GameObject Dungeon.VoronoiGenerator.pillar private
Pillar prefab placed at room intersections and map corners.
Definition at line 22 of file VoronoiGenerator.cs.
Referenced by PlacePillars().
rockCount
int Dungeon.VoronoiGenerator.rockCount = 80 private
Number of rocks to spawn.
Definition at line 114 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
rockPrefabs
List<GameObject> Dungeon.VoronoiGenerator.rockPrefabs private
Rock prefabs for scattering.
Definition at line 94 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
showBisectors
bool Dungeon.VoronoiGenerator.showBisectors = true private
Show triangle bisectors.
Definition at line 208 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showCenters
bool Dungeon.VoronoiGenerator.showCenters = true private
Show circumcenters used by Voronoi.
Definition at line 183 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showDoorEdgeID
bool Dungeon.VoronoiGenerator.showDoorEdgeID = true private
Show edge IDs and placed door IDs.
Definition at line 198 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showPoints
bool Dungeon.VoronoiGenerator.showPoints = true private
Show generated points in the scene view.
Definition at line 178 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showShortestItemPath
bool Dungeon.VoronoiGenerator.showShortestItemPath = true private
Show the computed shortest path to an item room.
Definition at line 193 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showSuperTriangle
bool Dungeon.VoronoiGenerator.showSuperTriangle = true private
Show the super triangle used during triangulation.
Definition at line 218 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showTriangles
bool Dungeon.VoronoiGenerator.showTriangles = true private
Show Delaunay triangles.
Definition at line 188 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showVoronoi
bool Dungeon.VoronoiGenerator.showVoronoi = true private
Show Voronoi edges.
Definition at line 203 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
showVoronoiIntersections
bool Dungeon.VoronoiGenerator.showVoronoiIntersections = true private
Show intersection points with the map boundary.
Definition at line 213 of file VoronoiGenerator.cs.
Referenced by OnDrawGizmos().
size
float Dungeon.VoronoiGenerator.size = 40 private
Side length of the square dungeon area.
Definition at line 58 of file VoronoiGenerator.cs.
Referenced by BowyerWatson(), BuildDungeon(), BuildRoomGraph(), CreateWall(), GenerateDebugData(), GenerateVoronoi(), PlacePillars(), RandomizeSizeAndPoints(), and ScatterCategory().
skyboxMaterials
Material [] Dungeon.VoronoiGenerator.skyboxMaterials private
Skybox materials rotated based on the seed.
Definition at line 73 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
spawnMargin
float Dungeon.VoronoiGenerator.spawnMargin = 1f private
Margin from the outer walls used when scattering props.
Definition at line 119 of file VoronoiGenerator.cs.
Referenced by ScatterCategory().
spawnY
float Dungeon.VoronoiGenerator.spawnY private
Y position for scattered props.
Definition at line 124 of file VoronoiGenerator.cs.
Referenced by ScatterCategory().
treeCount
int Dungeon.VoronoiGenerator.treeCount = 40 private
Number of trees to spawn.
Definition at line 109 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
treePrefabs
List<GameObject> Dungeon.VoronoiGenerator.treePrefabs private
Tree prefabs for scattering.
Definition at line 89 of file VoronoiGenerator.cs.
Referenced by BuildDungeon().
wall
GameObject Dungeon.VoronoiGenerator.wall private
Wall segment prefab for regular walls.
Definition at line 27 of file VoronoiGenerator.cs.
Referenced by CreateWallSegment().
Property Documentation
DungeonSize
float Dungeon.VoronoiGenerator.DungeonSize get
Public accessor for the current dungeon size.
Definition at line 129 of file VoronoiGenerator.cs.
ForcedItemRoomId
int Dungeon.VoronoiGenerator.ForcedItemRoomId = -1 get private set
ID of the chosen item room used for the forced path (-1 if none).
Definition at line 134 of file VoronoiGenerator.cs.
Referenced by ComputeDebugShortestItemPath(), and ComputeForcedDoorPairs().
The documentation for this class was generated from the following file:
VoronoiGenerator.cs