Projektarbeit 24/25: Interaction.LevelExitInteraction Class Reference
Interaction.LevelExitInteraction Class Reference
Handles player interaction with the level exit. When the player interacts, the level is advanced, player stats and inventory are saved, and the next scene is loaded. Also prevents enemies from reporting deaths during scene transitions.
Public Member Functions
void Interact (GameObject interactor)
Triggered when the player interacts with the level exit. Saves the player's inventory, equipment, and stats, advances the level, and loads the next scene. Ensures only the player can trigger this interaction.
void OnExit (GameObject interactor)
Required by IInteractable, but not used for the level exit.
bool ShouldRepeat ()
Indicates whether the interaction can be repeated. Level exit interaction is one-time only, so returns false.
Detailed Description
Handles player interaction with the level exit. When the player interacts, the level is advanced, player stats and inventory are saved, and the next scene is loaded. Also prevents enemies from reporting deaths during scene transitions.
Definition at line 15 of file LevelExitInteraction.cs.
Member Function Documentation
Interact()
void Interaction.LevelExitInteraction.Interact (GameObject interactor) inline
Triggered when the player interacts with the level exit. Saves the player's inventory, equipment, and stats, advances the level, and loads the next scene. Ensures only the player can trigger this interaction.
Parameters
interactor The GameObject interacting with the exit.
Implements Interfaces.IInteractable.
Definition at line 23 of file LevelExitInteraction.cs.
References Manager.SaveSystemManager.AdvanceLevel(), Stats.Stats.GetCurStatsList(), Manager.SaveSystemManager.SetEquipment(), Manager.SaveSystemManager.SetInventory(), Enemy.EnemyDeathReporter.SetSceneChanging(), and Manager.SaveSystemManager.SetStats().
OnExit()
void Interaction.LevelExitInteraction.OnExit (GameObject interactor) inline
Required by IInteractable, but not used for the level exit.
Parameters
interactor The GameObject leaving interaction range.
Implements Interfaces.IInteractable.
Definition at line 60 of file LevelExitInteraction.cs.
ShouldRepeat()
bool Interaction.LevelExitInteraction.ShouldRepeat ()
Indicates whether the interaction can be repeated. Level exit interaction is one-time only, so returns false.
Returns
False, interaction should not repeat.
Implements Interfaces.IInteractable.
The documentation for this class was generated from the following file:
LevelExitInteraction.cs