Projektarbeit 24/25: Saving.SaveData Class Reference
Saving.SaveData Class Reference
Serializable save container for global state, dungeon state, player state, and inventory.
Public Attributes
int Seed = 0
Random seed used for generation.
int Level = 0
Current level number.
int CurrentRoomID
ID of the current room.
bool BossRoomOpen = false
True if the boss room door is open.
bool BossCleared = false
True if the boss fight is cleared.
List< bool > VisitedRooms = new()
Visited state for each room (true = visited).
List< bool > DestroyableWallsActive = new()
Active state for each destroyable wall.
List< int > DestroyableWallsHealth = new()
Health values for each destroyable wall.
bool DigitMiniGameCleared = false
True if the digit mini-game is cleared.
bool GlyphMiniGameCleared = false
True if the glyph mini-game is cleared.
Vector3 PlayerPosition = new(0,0,0)
Saved player position.
Vector3 PlayerForward = new(0,0,0)
Saved player forward direction.
Vector3 CameraForward = new(0,0,0)
Saved camera forward direction.
List< float > CurrentStats = new()
Current stat values.
List< float > MaxStats = new()
Max stat values.
List< bool > Items = new()
Owned items flags per item index.
ItemInstance[] Inventory = new ItemInstance[4 * 5]
Saved inventory slots.
ItemInstance[] Equipment = new ItemInstance[3 * 2]
Saved equipment slots.
Detailed Description
Serializable save container for global state, dungeon state, player state, and inventory.
Definition at line 10 of file SaveData.cs.
Member Data Documentation
BossCleared
bool Saving.SaveData.BossCleared = false
True if the boss fight is cleared.
Definition at line 39 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetBossCleared().
BossRoomOpen
bool Saving.SaveData.BossRoomOpen = false
True if the boss room door is open.
Definition at line 34 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetBossRoomOpen().
CameraForward
Vector3 Saving.SaveData.CameraForward = new(0,0,0)
Saved camera forward direction.
Definition at line 81 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetCamRotation().
CurrentRoomID
int Saving.SaveData.CurrentRoomID
ID of the current room.
Definition at line 29 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetCurrentRoomID().
CurrentStats
List<float> Saving.SaveData.CurrentStats = new()
Current stat values.
Definition at line 86 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.SetStats().
DestroyableWallsActive
List<bool> Saving.SaveData.DestroyableWallsActive = new()
Active state for each destroyable wall.
Definition at line 49 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.GetDestroyableWallsActive().
DestroyableWallsHealth
List<int> Saving.SaveData.DestroyableWallsHealth = new()
Health values for each destroyable wall.
Definition at line 54 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.GetDestroyableWallsHealth().
DigitMiniGameCleared
bool Saving.SaveData.DigitMiniGameCleared = false
True if the digit mini-game is cleared.
Definition at line 59 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel().
Equipment
ItemInstance [] Saving.SaveData.Equipment = new ItemInstance[3 * 2]
Saved equipment slots.
Definition at line 110 of file SaveData.cs.
GlyphMiniGameCleared
bool Saving.SaveData.GlyphMiniGameCleared = false
True if the glyph mini-game is cleared.
Definition at line 64 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel().
Inventory
ItemInstance [] Saving.SaveData.Inventory = new ItemInstance[4 * 5]
Saved inventory slots.
Definition at line 105 of file SaveData.cs.
Items
List<bool> Saving.SaveData.Items = new()
Owned items flags per item index.
Definition at line 98 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), Manager.SaveSystemManager.IsCollectibleActive(), and Manager.SaveSystemManager.SetCollectibleActive().
Level
int Saving.SaveData.Level = 0
Current level number.
Definition at line 22 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel().
MaxStats
List<float> Saving.SaveData.MaxStats = new()
Max stat values.
Definition at line 91 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.SetStats().
PlayerForward
Vector3 Saving.SaveData.PlayerForward = new(0,0,0)
Saved player forward direction.
Definition at line 76 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetPlayerRotation().
PlayerPosition
Vector3 Saving.SaveData.PlayerPosition = new(0,0,0)
Saved player position.
Definition at line 71 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.SetPlayerPosition().
Seed
int Saving.SaveData.Seed = 0
Random seed used for generation.
Definition at line 17 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel().
VisitedRooms
List<bool> Saving.SaveData.VisitedRooms = new()
Visited state for each room (true = visited).
Definition at line 44 of file SaveData.cs.
Referenced by Manager.SaveSystemManager.AdvanceLevel(), and Manager.SaveSystemManager.InitializeVisitedRooms().
The documentation for this class was generated from the following file:
SaveData.cs