Projektarbeit 24/25: Manager.UIManager Class Reference
Manager.UIManager Class Reference
Central UI controller for panels, overlays, and text. Handles pause, inventory, mini-map, and game-over screens, and enables/disables player controls as needed.
Public Member Functions
void SetPlayer (GameObject newPlayer)
Assigns the player reference and caches important components.
void ShowPanel (string newText)
Updates the text on the UI panel and makes the panel visible.
void HidePanel ()
Hides the UI panel by deactivating the GameObject that contains the TMP_Text component.
Properties
static UIManager Instance [get, private set]
Singleton instance of the UIManager, ensuring there is only one instance in the scene. Provides global access to UI management functionality.
Private Member Functions
void Awake ()
Ensures there is only one instance of the UIManager in the scene. If another instance exists, it will be destroyed to maintain the singleton pattern. Persists this instance across scenes to provide consistent UI management.
void Start ()
Finds the inventory grid under the UI hierarchy.
void Update ()
Per-frame UI/state handling:
void OnEnable ()
Subscribes to door events to lock/unlock combat overlays.
void OnDisable ()
Unsubscribes from door events.
void HandleCloseDoors ()
Called when regular doors close (combat start).
void HandleOpenDoors ()
Called when regular doors open (combat end).
void HandleCloseBossDoors ()
Called when boss doors close (boss start).
void HandleOpenBossDoors ()
Called when boss doors open (boss end).
void EnterCombatLock ()
Enables combat lock. Closes pause if it is open.
void ExitCombatLock ()
Disables combat lock.
void CloseAllUIExcept (string except)
Closes all overlays except the named one.
void ResumeGameplayIfNotGameOver ()
Ensures gameplay is running (if not in game-over).
void EnableGameplay ()
Turns on movement and shooting controls (if present).
void DisableGameplay ()
Turns off movement and shooting controls (if present).
Private Attributes
TMP_Text tmpText
Text element used for small on-screen messages.
RectTransform pause
Pause menu root.
RectTransform gameOver
Game-over screen root.
TMP_Text pauseLevelText
Level text on the pause menu.
TMP_Text gameOverLevelText
Level text on the game-over screen.
GameObject miniMapPanel
Mini-map panel root.
bool _gameOverShown
Internal flag to print game-over info only once.
bool _isCombatLocked
True while combat locks out pause/inventory.
bool _isPauseVisible
True while the pause menu is visible.
GameObject _player
Cached player reference.
FirstPersonPlayerController _controller
Cached movement controller on the player.
PlayerShooting _shooter
Cached shooting component on the player.
bool _isInvVisible
True while the inventory UI is visible.
GameObject _itemUI
Reference to the inventory items grid object.
InventoryManager _inventoryManager
Inventory UI logic component.
Detailed Description
Central UI controller for panels, overlays, and text. Handles pause, inventory, mini-map, and game-over screens, and enables/disables player controls as needed.
Definition at line 14 of file UIManager.cs.
Member Function Documentation
Awake()
void Manager.UIManager.Awake () inline private
Ensures there is only one instance of the UIManager in the scene. If another instance exists, it will be destroyed to maintain the singleton pattern. Persists this instance across scenes to provide consistent UI management.
Definition at line 108 of file UIManager.cs.
References _inventoryManager, and Instance.
CloseAllUIExcept()
void Manager.UIManager.CloseAllUIExcept (string except) inline private
Closes all overlays except the named one.
Parameters
except Overlay to keep open: "pause", "inventory", or "map". Use null to close all.
Definition at line 405 of file UIManager.cs.
References _isInvVisible, _isPauseVisible, _itemUI, miniMapPanel, and pause.
Referenced by Update().
DisableGameplay()
void Manager.UIManager.DisableGameplay () inline private
Turns off movement and shooting controls (if present).
Definition at line 447 of file UIManager.cs.
References _controller, and _shooter.
Referenced by Update().
EnableGameplay()
void Manager.UIManager.EnableGameplay () inline private
Turns on movement and shooting controls (if present).
Definition at line 438 of file UIManager.cs.
References _controller, and _shooter.
Referenced by ResumeGameplayIfNotGameOver(), and Update().
EnterCombatLock()
void Manager.UIManager.EnterCombatLock () inline private
Enables combat lock. Closes pause if it is open.
Definition at line 379 of file UIManager.cs.
References _isCombatLocked, _isPauseVisible, Manager.GameInputManager.Instance, Manager.GameInputManager.MouseLocked(), and pause.
ExitCombatLock()
void Manager.UIManager.ExitCombatLock () inline private
Disables combat lock.
Definition at line 393 of file UIManager.cs.
References _isCombatLocked.
HandleCloseBossDoors()
void Manager.UIManager.HandleCloseBossDoors () private
Called when boss doors close (boss start).
Referenced by OnDisable(), and OnEnable().
HandleCloseDoors()
void Manager.UIManager.HandleCloseDoors () private
Called when regular doors close (combat start).
Referenced by OnDisable(), and OnEnable().
HandleOpenBossDoors()
void Manager.UIManager.HandleOpenBossDoors () private
Called when boss doors open (boss end).
Referenced by OnDisable(), and OnEnable().
HandleOpenDoors()
void Manager.UIManager.HandleOpenDoors () private
Called when regular doors open (combat end).
Referenced by OnDisable(), and OnEnable().
HidePanel()
void Manager.UIManager.HidePanel () inline
Hides the UI panel by deactivating the GameObject that contains the TMP_Text component.
Definition at line 165 of file UIManager.cs.
References tmpText.
Referenced by Interaction.DestroyableWallInteraction.Interact(), Interaction.DestroyableWallInteraction.OnExit(), MiniGame.DrawingTrigger.OnExit(), and Update().
OnDisable()
void Manager.UIManager.OnDisable () inline private
Unsubscribes from door events.
Definition at line 348 of file UIManager.cs.
References HandleCloseBossDoors(), HandleCloseDoors(), HandleOpenBossDoors(), HandleOpenDoors(), Manager.EventManager.OnCloseBossDoors, Manager.EventManager.OnCloseDoors, Manager.EventManager.OnOpenBossDoors, and Manager.EventManager.OnOpenDoors.
OnEnable()
void Manager.UIManager.OnEnable () inline private
Subscribes to door events to lock/unlock combat overlays.
Definition at line 337 of file UIManager.cs.
References HandleCloseBossDoors(), HandleCloseDoors(), HandleOpenBossDoors(), HandleOpenDoors(), Manager.EventManager.OnCloseBossDoors, Manager.EventManager.OnCloseDoors, Manager.EventManager.OnOpenBossDoors, and Manager.EventManager.OnOpenDoors.
ResumeGameplayIfNotGameOver()
void Manager.UIManager.ResumeGameplayIfNotGameOver () inline private
Ensures gameplay is running (if not in game-over).
Definition at line 426 of file UIManager.cs.
References EnableGameplay(), gameOver, Manager.GameInputManager.Instance, and Manager.GameInputManager.MouseLocked().
Referenced by Update().
SetPlayer()
void Manager.UIManager.SetPlayer (GameObject newPlayer) inline
Assigns the player reference and caches important components.
Parameters
newPlayer The spawned player object.
Definition at line 125 of file UIManager.cs.
References _controller, _inventoryManager, _player, and _shooter.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
ShowPanel()
void Manager.UIManager.ShowPanel (string newText) inline
Updates the text on the UI panel and makes the panel visible.
Parameters
newText The new text to display on the UI panel.
Definition at line 150 of file UIManager.cs.
References tmpText.
Referenced by Interaction.DestroyableWallInteraction.Interact(), and MiniGame.DrawingTrigger.Interact().
Start()
void Manager.UIManager.Start () inline private
Finds the inventory grid under the UI hierarchy.
Definition at line 141 of file UIManager.cs.
References _itemUI.
Update()
void Manager.UIManager.Update () inline private
Per-frame UI/state handling:
Game-over when health < 1
Toggle pause with P
Toggle inventory with I
Toggle mini-map with M
Definition at line 177 of file UIManager.cs.
References _gameOverShown, _isCombatLocked, _isInvVisible, _isPauseVisible, _itemUI, _player, CloseAllUIExcept(), DisableGameplay(), EnableGameplay(), gameOver, gameOverLevelText, Stats.Stats.GetCurStats(), HidePanel(), Manager.GameInputManager.Instance, miniMapPanel, Manager.GameInputManager.MouseLocked(), pause, pauseLevelText, and ResumeGameplayIfNotGameOver().
Member Data Documentation
_controller
FirstPersonPlayerController Manager.UIManager._controller private
Cached movement controller on the player.
Definition at line 81 of file UIManager.cs.
Referenced by DisableGameplay(), EnableGameplay(), and SetPlayer().
_gameOverShown
bool Manager.UIManager._gameOverShown private
Internal flag to print game-over info only once.
Definition at line 61 of file UIManager.cs.
Referenced by Update().
_inventoryManager
InventoryManager Manager.UIManager._inventoryManager private
Inventory UI logic component.
Definition at line 101 of file UIManager.cs.
Referenced by Awake(), and SetPlayer().
_isCombatLocked
bool Manager.UIManager._isCombatLocked private
True while combat locks out pause/inventory.
Definition at line 66 of file UIManager.cs.
Referenced by EnterCombatLock(), ExitCombatLock(), and Update().
_isInvVisible
bool Manager.UIManager._isInvVisible private
True while the inventory UI is visible.
Definition at line 91 of file UIManager.cs.
Referenced by CloseAllUIExcept(), and Update().
_isPauseVisible
bool Manager.UIManager._isPauseVisible private
True while the pause menu is visible.
Definition at line 71 of file UIManager.cs.
Referenced by CloseAllUIExcept(), EnterCombatLock(), and Update().
_itemUI
GameObject Manager.UIManager._itemUI private
Reference to the inventory items grid object.
Definition at line 96 of file UIManager.cs.
Referenced by CloseAllUIExcept(), Start(), and Update().
_player
GameObject Manager.UIManager._player private
Cached player reference.
Definition at line 76 of file UIManager.cs.
Referenced by SetPlayer(), and Update().
_shooter
PlayerShooting Manager.UIManager._shooter private
Cached shooting component on the player.
Definition at line 86 of file UIManager.cs.
Referenced by DisableGameplay(), EnableGameplay(), and SetPlayer().
gameOver
RectTransform Manager.UIManager.gameOver private
Game-over screen root.
Definition at line 38 of file UIManager.cs.
Referenced by ResumeGameplayIfNotGameOver(), and Update().
gameOverLevelText
TMP_Text Manager.UIManager.gameOverLevelText private
Level text on the game-over screen.
Definition at line 50 of file UIManager.cs.
Referenced by Update().
miniMapPanel
GameObject Manager.UIManager.miniMapPanel private
Mini-map panel root.
Definition at line 56 of file UIManager.cs.
Referenced by CloseAllUIExcept(), and Update().
pause
RectTransform Manager.UIManager.pause private
Pause menu root.
Definition at line 32 of file UIManager.cs.
Referenced by CloseAllUIExcept(), EnterCombatLock(), and Update().
pauseLevelText
TMP_Text Manager.UIManager.pauseLevelText private
Level text on the pause menu.
Definition at line 44 of file UIManager.cs.
Referenced by Update().
tmpText
TMP_Text Manager.UIManager.tmpText private
Text element used for small on-screen messages.
Definition at line 26 of file UIManager.cs.
Referenced by HidePanel(), and ShowPanel().
Property Documentation
Instance
UIManager Manager.UIManager.Instance static get private set
Singleton instance of the UIManager, ensuring there is only one instance in the scene. Provides global access to UI management functionality.
Definition at line 20 of file UIManager.cs.
Referenced by Awake(), Interaction.DestroyableWallInteraction.Interact(), MiniGame.DrawingTrigger.Interact(), Interaction.DestroyableWallInteraction.OnExit(), MiniGame.DrawingTrigger.OnExit(), and Manager.GameManagerVoronoi.SpawnPlayer().
The documentation for this class was generated from the following file:
UIManager.cs