Projektarbeit 24/25: Spawning.BossSpawnerVoronoi Class Reference
Spawning.BossSpawnerVoronoi Class Reference
class to manage boss & obstacle spawning, setting the boss active and inactive and also spawning the exit prefab to leave current level and proceed
Public Member Functions
BossSpawnerVoronoi (Room bossRoom, List< GameObject > bossPrefabs, List< GameObject > obstaclePrefabs, Transform parent, GameObject levelExitPrefab=null)
constructor of Boss Spawner Voronoi which will set the members, creates the static instance, spawnes the boss prefab & obstacles in the corresponding bossRoom
void ActivateBossInRoom (Room room)
sets the boss' gameobjects in the corresponding room active
Static Public Member Functions
static void RegisterBossMinionSpawn (int roomId)
increases amount of living enemies in the corresponding room because the boss can spawn smaller enemies to his help
static void RegisterBossMinionDeath (int roomId)
reduces amount of living enemies in the corresponding room because the boss can spawn smaller enemies to his help
Private Member Functions
void OnBossEnemyDied (int roomId)
function that tracks if all enemies in the corresponding boss room have been defeated and the exit prefab has been spawned if yes it returns, else it will spawn the exit and sets _exitSpawned to true decreases living amount of the room
void SpawnLevelExit ()
instantiates level exit prefab to the correspoinding boss room and uses the parent of the room
void IncrementAlive (int roomId)
function that increases the tracker of the living enemies per room
Private Attributes
readonly Dictionary< int, List< GameObject > > _bossInstancesPerRoom = new()
Stores all bosses per room by room id as the key which are spawned.
readonly Dictionary< int, int > _alivePerRoom = new()
Stores the amount of enemies which are alive per boss room by room id as the key.
readonly int _bossRoomId = -1
stores the id of the current boss room
readonly Transform _parent
Parent transform under which the enemies are spawned.
readonly GameObject _levelExitPrefab
Prefab which will be spawned after the boss has been defeated.
Room _bossRoomRef
Room metadata object reference of the current boss room.
bool _exitSpawned
private bool member if the exit has been spawned already
Static Private Attributes
static BossSpawnerVoronoi _instance
static instance of BossSpawnerVoronoi
Detailed Description
class to manage boss & obstacle spawning, setting the boss active and inactive and also spawning the exit prefab to leave current level and proceed
Definition at line 15 of file BossSpawnerVoronoi.cs.
Constructor & Destructor Documentation
BossSpawnerVoronoi()
Spawning.BossSpawnerVoronoi.BossSpawnerVoronoi (Room bossRoom, List< GameObject > bossPrefabs, List< GameObject > obstaclePrefabs, Transform parent, GameObject levelExitPrefab = null) inline
constructor of Boss Spawner Voronoi which will set the members, creates the static instance, spawnes the boss prefab & obstacles in the corresponding bossRoom
Parameters
bossRoom room data of boss room into which the boss will be spawned
bossPrefabs List of boss prefabs which will be used to spawn
obstaclePrefabs List of prefabs that will be spawned as obstacles
parent Parent transform under which the enemies are spawned
levelExitPrefab Prefab which will be spawned after beating the boss
Definition at line 64 of file BossSpawnerVoronoi.cs.
References _alivePerRoom, _bossInstancesPerRoom, _bossRoomId, _bossRoomRef, _exitSpawned, _instance, _levelExitPrefab, _parent, Enemy.EnemyLevelScaler.Apply(), Dungeon.Room.Center, Manager.SaveSystemManager.GetBossCleared(), Dungeon.Room.GetIncircleRadius(), Dungeon.Room.ID, Enemy.EnemyDeathReporter.Init(), OnBossEnemyDied(), SpawnLevelExit(), Dungeon.Point.X, and Dungeon.Point.Y.
Member Function Documentation
ActivateBossInRoom()
void Spawning.BossSpawnerVoronoi.ActivateBossInRoom (Room room) inline
sets the boss' gameobjects in the corresponding room active
Parameters
room id to room where gameobjects/enemies should be activated
Definition at line 155 of file BossSpawnerVoronoi.cs.
References _bossInstancesPerRoom, _bossRoomId, and Dungeon.Room.ID.
IncrementAlive()
void Spawning.BossSpawnerVoronoi.IncrementAlive (int roomId) inline private
function that increases the tracker of the living enemies per room
Parameters
roomId id of boss room where living amount should be increased
Definition at line 235 of file BossSpawnerVoronoi.cs.
References _alivePerRoom.
OnBossEnemyDied()
void Spawning.BossSpawnerVoronoi.OnBossEnemyDied (int roomId) inline private
function that tracks if all enemies in the corresponding boss room have been defeated and the exit prefab has been spawned if yes it returns, else it will spawn the exit and sets _exitSpawned to true decreases living amount of the room
Parameters
roomId room id of the boss room where the boss has been defeated
Definition at line 172 of file BossSpawnerVoronoi.cs.
References _alivePerRoom, _bossRoomId, _exitSpawned, Manager.EventManager.Instance, Manager.SaveSystemManager.SetBossCleared(), Manager.SaveSystemManager.SetBossRoomOpen(), SpawnLevelExit(), and Manager.EventManager.TriggerOpenBossDoors().
Referenced by BossSpawnerVoronoi().
RegisterBossMinionDeath()
void Spawning.BossSpawnerVoronoi.RegisterBossMinionDeath (int roomId) inline static
reduces amount of living enemies in the corresponding room because the boss can spawn smaller enemies to his help
Parameters
roomId id of boss room where living amount should be decreased
Definition at line 226 of file BossSpawnerVoronoi.cs.
References _instance.
Referenced by Enemy.SpawnlingAutoRegister.Awake().
RegisterBossMinionSpawn()
void Spawning.BossSpawnerVoronoi.RegisterBossMinionSpawn (int roomId) inline static
increases amount of living enemies in the corresponding room because the boss can spawn smaller enemies to his help
Parameters
roomId id of boss room where living amount should be increased
Definition at line 217 of file BossSpawnerVoronoi.cs.
References _instance.
Referenced by Enemy.SpawnlingAutoRegister.Awake().
SpawnLevelExit()
void Spawning.BossSpawnerVoronoi.SpawnLevelExit () inline private
instantiates level exit prefab to the correspoinding boss room and uses the parent of the room
Definition at line 193 of file BossSpawnerVoronoi.cs.
References _bossRoomRef, _levelExitPrefab, and _parent.
Referenced by BossSpawnerVoronoi(), and OnBossEnemyDied().
Member Data Documentation
_alivePerRoom
readonly Dictionary<int, int> Spawning.BossSpawnerVoronoi._alivePerRoom = new() private
Stores the amount of enemies which are alive per boss room by room id as the key.
Definition at line 24 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), IncrementAlive(), and OnBossEnemyDied().
_bossInstancesPerRoom
readonly Dictionary<int, List<GameObject> > Spawning.BossSpawnerVoronoi._bossInstancesPerRoom = new() private
Stores all bosses per room by room id as the key which are spawned.
Definition at line 20 of file BossSpawnerVoronoi.cs.
Referenced by ActivateBossInRoom(), and BossSpawnerVoronoi().
_bossRoomId
readonly int Spawning.BossSpawnerVoronoi._bossRoomId = -1 private
stores the id of the current boss room
Definition at line 28 of file BossSpawnerVoronoi.cs.
Referenced by ActivateBossInRoom(), BossSpawnerVoronoi(), and OnBossEnemyDied().
_bossRoomRef
Room Spawning.BossSpawnerVoronoi._bossRoomRef private
Room metadata object reference of the current boss room.
Definition at line 43 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), and SpawnLevelExit().
_exitSpawned
bool Spawning.BossSpawnerVoronoi._exitSpawned private
private bool member if the exit has been spawned already
Definition at line 48 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), and OnBossEnemyDied().
_instance
BossSpawnerVoronoi Spawning.BossSpawnerVoronoi._instance static private
static instance of BossSpawnerVoronoi
Definition at line 53 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), RegisterBossMinionDeath(), and RegisterBossMinionSpawn().
_levelExitPrefab
readonly GameObject Spawning.BossSpawnerVoronoi._levelExitPrefab private
Prefab which will be spawned after the boss has been defeated.
Definition at line 38 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), and SpawnLevelExit().
_parent
readonly Transform Spawning.BossSpawnerVoronoi._parent private
Parent transform under which the enemies are spawned.
Definition at line 33 of file BossSpawnerVoronoi.cs.
Referenced by BossSpawnerVoronoi(), and SpawnLevelExit().
The documentation for this class was generated from the following file:
BossSpawnerVoronoi.cs