Projektarbeit 24/25: Manager.GameManagerVoronoi Class Reference
Manager.GameManagerVoronoi Class Reference
Runs the core game loop for the Voronoi dungeon: generates the level, spawns the player, tracks the current room, and reacts to room changes (enemies, boss, minigames, doors, items).
Public Member Functions
bool OnBossKeyUsed ()
Called by the BossKey when used. Opens boss doors if the player is next to the boss room.
Properties
static GameManagerVoronoi Instance [get, private set]
Singleton instance of the GameManagerVoronoi, ensuring there is only one instance in the scene. Provides global access to event management functionality.
DungeonGraph Graph [get]
Exposes the generated dungeon graph.
Room CurrentRoom [get]
Exposes the room the player is currently in.
Private Member Functions
void Awake ()
Ensures there is only one instance of the GameManagerVoronoi in the scene. If another instance exists, it will be destroyed. Persists the instance across scenes for consistent event state management.
void Start ()
Sets up the run: generate the dungeon, restore visited state, spawn the player, create spawners, and restore boss door state.
void GenerateDungeon ()
Builds the dungeon based on the saved seed.
void RestoreVisitedAndCurrentRoom ()
Restores visited flags and current room from the save. Initializes visited data if it does not match the new dungeon size.
void InitializeSpawners ()
Creates and runs spawners for items, minigames, enemies, and boss content. Also sets up glyph logic for this run.
void SpawnPlayer ()
Spawns the player at the start room or at the saved position, restores facing and camera, and wires up input and shooting.
void RestoreBossDoorState ()
Opens boss doors on load if the save says they are already open.
void Update ()
Called once per frame to track player behavior and transitions.
void TrackCurrentRoom ()
Checks player distance to current and neighbor rooms to detect a room switch. Calls OnRoomEntered when a new room is entered.
void OnRoomEntered (Room newRoom)
Called when the player enters a new room. Used to trigger room-specific game logic, such as boss activation, enemy activation, item placement, or door locking.
void PopulateDungeon ()
Runs all registered spawners to populate the dungeon.
IEnumerator OpenBossDoorsNextFrame ()
Opens boss doors on the next frame (used during a load).
Static Private Member Functions
static List< string > GetGlyphItem (List< int > glyphKeys)
Maps glyph key IDs to their item names and returns the list for this run.
static List< int > GenerateRandomGlyphs (int seed=-1)
Generates a random set of glyph IDs for the run.
Private Attributes
GameObject playerPrefab
The prefab used to instantiate the player at the start of the game.
VoronoiGenerator voronoiGenerator
Reference to the VoronoiGenerator responsible for dungeon generation.
float roomSwitchThreshold = 5f
Distance threshold used to determine when the player has left the current room.
List< ItemInstance > items
Regular items that can appear in item rooms.
List< ItemInstance > mustItems
Items that must be available.
List< ItemInstance > glyphItems
Prefabs for Glyph Items.
List< GameObject > miniGamePrefabs
Prefabs for possible minigames.
List< GameObject > enemyPrefabs
Prefabs for regular enemies.
List< GameObject > bossEnemyPrefabs
Prefabs for boss enemies.
List< GameObject > obstaclePrefabs
Prefabs for room obstacles used in boss arenas.
GameObject levelExitPrefab
Prefab for the level exit after defeating the boss.
GameObject _player
The instantiated player.
DungeonGraph _dungeon
Active dungeon graph for this run.
Room _currentRoom
The Room the player is currently in.
List< ISpawnerVoronoi > _spawners
Active content spawners (items, minigames, etc.).
EnemySpawnerVoronoi _enemySpawner
Spawner that manages regular enemies.
BossSpawnerVoronoi _bossSpawner
Spawner that manages the boss room.
Detailed Description
Runs the core game loop for the Voronoi dungeon: generates the level, spawns the player, tracks the current room, and reacts to room changes (enemies, boss, minigames, doors, items).
Definition at line 22 of file GameManagerVoronoi.cs.
Member Function Documentation
Awake()
void Manager.GameManagerVoronoi.Awake () inline private
Ensures there is only one instance of the GameManagerVoronoi in the scene. If another instance exists, it will be destroyed. Persists the instance across scenes for consistent event state management.
Definition at line 130 of file GameManagerVoronoi.cs.
References Instance.
GenerateDungeon()
void Manager.GameManagerVoronoi.GenerateDungeon () inline private
Builds the dungeon based on the saved seed.
Definition at line 159 of file GameManagerVoronoi.cs.
References _dungeon, Manager.SaveSystemManager.GetSeed(), and voronoiGenerator.
Referenced by Start().
GenerateRandomGlyphs()
List< int > Manager.GameManagerVoronoi.GenerateRandomGlyphs (int seed = -1) inline static private
Generates a random set of glyph IDs for the run.
Parameters
seed Seed from the save; if negative, a random seed is used.
Returns
List of unique glyph IDs.
Definition at line 274 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
GetGlyphItem()
List< string > Manager.GameManagerVoronoi.GetGlyphItem (List< int > glyphKeys) inline static private
Maps glyph key IDs to their item names and returns the list for this run.
Parameters
glyphKeys Glyph IDs selected for the run.
Returns
List of glyph item names.
Definition at line 245 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
InitializeSpawners()
void Manager.GameManagerVoronoi.InitializeSpawners () inline private
Creates and runs spawners for items, minigames, enemies, and boss content. Also sets up glyph logic for this run.
Definition at line 194 of file GameManagerVoronoi.cs.
References _bossSpawner, _dungeon, _enemySpawner, _spawners, bossEnemyPrefabs, enemyPrefabs, GenerateRandomGlyphs(), GetGlyphItem(), Manager.SaveSystemManager.GetSeed(), glyphItems, items, levelExitPrefab, miniGamePrefabs, mustItems, obstaclePrefabs, PopulateDungeon(), MiniGame.CanvasDraw.SetRefGlyph, and voronoiGenerator.
Referenced by Start().
OnBossKeyUsed()
bool Manager.GameManagerVoronoi.OnBossKeyUsed () inline
Called by the BossKey when used. Opens boss doors if the player is next to the boss room.
Returns
True if the key was used in a valid spot, otherwise false.
Definition at line 457 of file GameManagerVoronoi.cs.
References _currentRoom, _dungeon, Manager.EventManager.Instance, Manager.SaveSystemManager.SetBossRoomOpen(), and Manager.EventManager.TriggerOpenBossDoors().
Referenced by Items.BossKey.Use().
OnRoomEntered()
void Manager.GameManagerVoronoi.OnRoomEntered (Room newRoom) inline private
Called when the player enters a new room. Used to trigger room-specific game logic, such as boss activation, enemy activation, item placement, or door locking.
Parameters
newRoom The room that the player just entered.
Definition at line 406 of file GameManagerVoronoi.cs.
References _bossSpawner, _enemySpawner, Dungeon.Room.ID, Manager.EventManager.Instance, Manager.SaveSystemManager.SetCurrentRoomID(), Manager.SaveSystemManager.SetRoomVisited(), Manager.EventManager.TriggerCloseBossDoors(), Manager.EventManager.TriggerCloseDoors(), Dungeon.Room.Type, and Dungeon.Room.Visited.
Referenced by SpawnPlayer(), and TrackCurrentRoom().
OpenBossDoorsNextFrame()
IEnumerator Manager.GameManagerVoronoi.OpenBossDoorsNextFrame () inline private
Opens boss doors on the next frame (used during a load).
Returns
Coroutine handle.
Definition at line 478 of file GameManagerVoronoi.cs.
References Manager.EventManager.Instance, and Manager.EventManager.TriggerOpenBossDoors().
Referenced by RestoreBossDoorState().
PopulateDungeon()
void Manager.GameManagerVoronoi.PopulateDungeon () inline private
Runs all registered spawners to populate the dungeon.
Definition at line 444 of file GameManagerVoronoi.cs.
References _spawners.
Referenced by InitializeSpawners().
RestoreBossDoorState()
void Manager.GameManagerVoronoi.RestoreBossDoorState () inline private
Opens boss doors on load if the save says they are already open.
Definition at line 354 of file GameManagerVoronoi.cs.
References Manager.SaveSystemManager.GetBossRoomOpen(), and OpenBossDoorsNextFrame().
Referenced by Start().
RestoreVisitedAndCurrentRoom()
void Manager.GameManagerVoronoi.RestoreVisitedAndCurrentRoom () inline private
Restores visited flags and current room from the save. Initializes visited data if it does not match the new dungeon size.
Definition at line 170 of file GameManagerVoronoi.cs.
References _currentRoom, _dungeon, Manager.SaveSystemManager.GetCurrentRoomID(), Manager.SaveSystemManager.GetVisitedRooms(), Manager.SaveSystemManager.InitializeVisitedRooms(), Manager.SaveSystemManager.SetCurrentRoomID(), and Manager.SaveSystemManager.SetRoomVisited().
Referenced by Start().
SpawnPlayer()
void Manager.GameManagerVoronoi.SpawnPlayer () inline private
Spawns the player at the start room or at the saved position, restores facing and camera, and wires up input and shooting.
Definition at line 296 of file GameManagerVoronoi.cs.
References _currentRoom, _dungeon, _player, Manager.SaveSystemManager.GetCamRotation(), Manager.SaveSystemManager.GetPlayerPosition(), Manager.SaveSystemManager.GetPlayerRotation(), Manager.SaveSystemManager.GetStats(), Shooting.PlayerShooting.Init(), Manager.CameraManager.Instance, Manager.UIManager.Instance, OnRoomEntered(), playerPrefab, Manager.SaveSystemManager.SetCamRotation(), Manager.CameraManager.SetPlayer(), Manager.UIManager.SetPlayer(), Manager.SaveSystemManager.SetPlayerPosition(), and Manager.SaveSystemManager.SetPlayerRotation().
Referenced by Start().
Start()
void Manager.GameManagerVoronoi.Start () inline private
Sets up the run: generate the dungeon, restore visited state, spawn the player, create spawners, and restore boss door state.
Definition at line 145 of file GameManagerVoronoi.cs.
References GenerateDungeon(), InitializeSpawners(), RestoreBossDoorState(), RestoreVisitedAndCurrentRoom(), Enemy.EnemyDeathReporter.SetSceneChanging(), and SpawnPlayer().
TrackCurrentRoom()
void Manager.GameManagerVoronoi.TrackCurrentRoom () inline private
Checks player distance to current and neighbor rooms to detect a room switch. Calls OnRoomEntered when a new room is entered.
Definition at line 374 of file GameManagerVoronoi.cs.
References _currentRoom, _player, OnRoomEntered(), and roomSwitchThreshold.
Referenced by Update().
Update()
void Manager.GameManagerVoronoi.Update () inline private
Called once per frame to track player behavior and transitions.
Definition at line 363 of file GameManagerVoronoi.cs.
References _currentRoom, _dungeon, _player, and TrackCurrentRoom().
Member Data Documentation
_bossSpawner
BossSpawnerVoronoi Manager.GameManagerVoronoi._bossSpawner private
Spawner that manages the boss room.
Definition at line 123 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners(), and OnRoomEntered().
_currentRoom
Room Manager.GameManagerVoronoi._currentRoom private
The Room the player is currently in.
Definition at line 108 of file GameManagerVoronoi.cs.
Referenced by OnBossKeyUsed(), RestoreVisitedAndCurrentRoom(), SpawnPlayer(), TrackCurrentRoom(), and Update().
_dungeon
DungeonGraph Manager.GameManagerVoronoi._dungeon private
Active dungeon graph for this run.
Definition at line 103 of file GameManagerVoronoi.cs.
Referenced by GenerateDungeon(), InitializeSpawners(), OnBossKeyUsed(), RestoreVisitedAndCurrentRoom(), SpawnPlayer(), and Update().
_enemySpawner
EnemySpawnerVoronoi Manager.GameManagerVoronoi._enemySpawner private
Spawner that manages regular enemies.
Definition at line 118 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners(), and OnRoomEntered().
_player
GameObject Manager.GameManagerVoronoi._player private
The instantiated player.
Definition at line 98 of file GameManagerVoronoi.cs.
Referenced by SpawnPlayer(), TrackCurrentRoom(), and Update().
_spawners
List<ISpawnerVoronoi> Manager.GameManagerVoronoi._spawners private
Active content spawners (items, minigames, etc.).
Definition at line 113 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners(), and PopulateDungeon().
bossEnemyPrefabs
List<GameObject> Manager.GameManagerVoronoi.bossEnemyPrefabs private
Prefabs for boss enemies.
Definition at line 73 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
enemyPrefabs
List<GameObject> Manager.GameManagerVoronoi.enemyPrefabs private
Prefabs for regular enemies.
Definition at line 68 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
glyphItems
List<ItemInstance> Manager.GameManagerVoronoi.glyphItems private
Prefabs for Glyph Items.
Definition at line 58 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
items
List<ItemInstance> Manager.GameManagerVoronoi.items private
Regular items that can appear in item rooms.
Definition at line 48 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
levelExitPrefab
GameObject Manager.GameManagerVoronoi.levelExitPrefab private
Prefab for the level exit after defeating the boss.
Definition at line 83 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
miniGamePrefabs
List<GameObject> Manager.GameManagerVoronoi.miniGamePrefabs private
Prefabs for possible minigames.
Definition at line 63 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
mustItems
List<ItemInstance> Manager.GameManagerVoronoi.mustItems private
Items that must be available.
Definition at line 53 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
obstaclePrefabs
List<GameObject> Manager.GameManagerVoronoi.obstaclePrefabs private
Prefabs for room obstacles used in boss arenas.
Definition at line 78 of file GameManagerVoronoi.cs.
Referenced by InitializeSpawners().
playerPrefab
GameObject Manager.GameManagerVoronoi.playerPrefab private
The prefab used to instantiate the player at the start of the game.
Definition at line 33 of file GameManagerVoronoi.cs.
Referenced by SpawnPlayer().
roomSwitchThreshold
float Manager.GameManagerVoronoi.roomSwitchThreshold = 5f private
Distance threshold used to determine when the player has left the current room.
Definition at line 43 of file GameManagerVoronoi.cs.
Referenced by TrackCurrentRoom().
voronoiGenerator
VoronoiGenerator Manager.GameManagerVoronoi.voronoiGenerator private
Reference to the VoronoiGenerator responsible for dungeon generation.
Definition at line 38 of file GameManagerVoronoi.cs.
Referenced by GenerateDungeon(), and InitializeSpawners().
Property Documentation
CurrentRoom
Room Manager.GameManagerVoronoi.CurrentRoom get
Exposes the room the player is currently in.
Definition at line 93 of file GameManagerVoronoi.cs.
Referenced by Enemy.SpawnlingAutoRegister.Awake().
Graph
DungeonGraph Manager.GameManagerVoronoi.Graph get
Exposes the generated dungeon graph.
Definition at line 88 of file GameManagerVoronoi.cs.
Instance
GameManagerVoronoi Manager.GameManagerVoronoi.Instance static get private set
Singleton instance of the GameManagerVoronoi, ensuring there is only one instance in the scene. Provides global access to event management functionality.
Definition at line 28 of file GameManagerVoronoi.cs.
Referenced by Enemy.SpawnlingAutoRegister.Awake(), Awake(), and Items.BossKey.Use().
The documentation for this class was generated from the following file:
GameManagerVoronoi.cs