Projektarbeit 24/25: Manager.MiniMapManager Class Reference
Manager.MiniMapManager Class Reference
Renders a runtime minimap of Voronoi‐generated dungeon rooms, connections, and player orientation.
Private Member Functions
void Awake ()
Validates dependencies and caches the main camera.
void Start ()
Starts initialization once the dungeon is ready.
IEnumerator InitWhenReady ()
Waits for the dungeon to be generated, then builds icons and connections. Also snap the player icon to the start room.
void GenerateRoomIcons ()
Instantiates and positions a square + label for each room in the dungeon.
void GenerateConnections ()
Draws connection lines between neighboring rooms.
void Update ()
Refresh room visuals and player icon.
void RefreshRoomStates ()
Updates colors and labels for rooms whose visited state changed.
void UpdatePlayerIcon ()
Positions the player icon over its current room and rotates the visual arrow to match facing directions.
Private Attributes
GameManagerVoronoi gameManager
Reference to the main game manager (provides the current room).
VoronoiGenerator voronoiGenerator
Reference to the Voronoi generator (provides the dungeon graph and size).
RectTransform minimapRect
Root RectTransform of the minimap UI.
RectTransform roomsContainer
Parent container for room icons.
RectTransform connectionsContainer
Parent container for connection lines.
RectTransform playerIcon
RectTransform of the player icon root.
RectTransform playerIconVisual
Visual part of the player icon (rotated to show facing).
GameObject roomIconPrefab
Prefab used for each room icon.
GameObject linePrefab
Prefab used for connection lines between rooms.
float lineThickness = 2f
Line thickness for connections.
Vector2 lineOffset = new(8f, 8f)
Small offset applied to the start position of each connection line.
Color visitedColor = Color.white
Color for visited rooms.
Color unvisitedColor = new(0.5f, 0.5f, 0.5f)
Color for unvisited rooms.
DungeonGraph _dungeon
Generated dungeon graph (rooms and neighbors).
float _dungeonSize
World size used to map room positions onto the minimap.
Camera _mainCamera
Cached the main camera for reading the player yaw.
readonly Dictionary< int, RectTransform > _roomIcons = new()
Lookup from room id to its icon RectTransform.
readonly Dictionary< int, Image > _roomImages = new()
Lookup from room id to its icon Image (for color updates).
readonly Dictionary< int, TMP_Text > _roomLabels = new()
Lookup from room id to its label (shown when visited).
readonly List< GameObject > _connectionLines = new()
Pool of active connection line objects.
Detailed Description
Renders a runtime minimap of Voronoi‐generated dungeon rooms, connections, and player orientation.
Definition at line 13 of file MiniMapManager.cs.
Member Function Documentation
Awake()
void Manager.MiniMapManager.Awake () inline private
Validates dependencies and caches the main camera.
Definition at line 122 of file MiniMapManager.cs.
References _mainCamera, gameManager, and voronoiGenerator.
GenerateConnections()
void Manager.MiniMapManager.GenerateConnections () inline private
Draws connection lines between neighboring rooms.
Definition at line 204 of file MiniMapManager.cs.
References _connectionLines, _dungeon, _roomIcons, connectionsContainer, lineOffset, linePrefab, and lineThickness.
Referenced by InitWhenReady().
GenerateRoomIcons()
void Manager.MiniMapManager.GenerateRoomIcons () inline private
Instantiates and positions a square + label for each room in the dungeon.
Definition at line 165 of file MiniMapManager.cs.
References _dungeon, _dungeonSize, _roomIcons, _roomImages, _roomLabels, minimapRect, playerIcon, roomIconPrefab, roomsContainer, unvisitedColor, and visitedColor.
Referenced by InitWhenReady().
InitWhenReady()
IEnumerator Manager.MiniMapManager.InitWhenReady () inline private
Waits for the dungeon to be generated, then builds icons and connections. Also snap the player icon to the start room.
Definition at line 146 of file MiniMapManager.cs.
References _dungeon, _dungeonSize, _roomIcons, gameManager, GenerateConnections(), GenerateRoomIcons(), and voronoiGenerator.
Referenced by Start().
RefreshRoomStates()
void Manager.MiniMapManager.RefreshRoomStates () inline private
Updates colors and labels for rooms whose visited state changed.
Definition at line 245 of file MiniMapManager.cs.
References _dungeon, _roomImages, _roomLabels, unvisitedColor, and visitedColor.
Referenced by Update().
Start()
void Manager.MiniMapManager.Start () inline private
Starts initialization once the dungeon is ready.
Definition at line 137 of file MiniMapManager.cs.
References InitWhenReady().
Update()
void Manager.MiniMapManager.Update () inline private
Refresh room visuals and player icon.
Definition at line 236 of file MiniMapManager.cs.
References RefreshRoomStates(), and UpdatePlayerIcon().
UpdatePlayerIcon()
void Manager.MiniMapManager.UpdatePlayerIcon () inline private
Positions the player icon over its current room and rotates the visual arrow to match facing directions.
Definition at line 262 of file MiniMapManager.cs.
References _mainCamera, _roomIcons, gameManager, and playerIconVisual.
Referenced by Update().
Member Data Documentation
_connectionLines
readonly List<GameObject> Manager.MiniMapManager._connectionLines = new() private
Pool of active connection line objects.
Definition at line 117 of file MiniMapManager.cs.
Referenced by GenerateConnections().
_dungeon
DungeonGraph Manager.MiniMapManager._dungeon private
Generated dungeon graph (rooms and neighbors).
Definition at line 87 of file MiniMapManager.cs.
Referenced by GenerateConnections(), GenerateRoomIcons(), InitWhenReady(), and RefreshRoomStates().
_dungeonSize
float Manager.MiniMapManager._dungeonSize private
World size used to map room positions onto the minimap.
Definition at line 92 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons(), and InitWhenReady().
_mainCamera
Camera Manager.MiniMapManager._mainCamera private
Cached the main camera for reading the player yaw.
Definition at line 97 of file MiniMapManager.cs.
Referenced by Awake(), and UpdatePlayerIcon().
_roomIcons
readonly Dictionary<int, RectTransform> Manager.MiniMapManager._roomIcons = new() private
Lookup from room id to its icon RectTransform.
Definition at line 102 of file MiniMapManager.cs.
Referenced by GenerateConnections(), GenerateRoomIcons(), InitWhenReady(), and UpdatePlayerIcon().
_roomImages
readonly Dictionary<int, Image> Manager.MiniMapManager._roomImages = new() private
Lookup from room id to its icon Image (for color updates).
Definition at line 107 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons(), and RefreshRoomStates().
_roomLabels
readonly Dictionary<int, TMP_Text> Manager.MiniMapManager._roomLabels = new() private
Lookup from room id to its label (shown when visited).
Definition at line 112 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons(), and RefreshRoomStates().
connectionsContainer
RectTransform Manager.MiniMapManager.connectionsContainer private
Parent container for connection lines.
Definition at line 40 of file MiniMapManager.cs.
Referenced by GenerateConnections().
gameManager
GameManagerVoronoi Manager.MiniMapManager.gameManager private
Reference to the main game manager (provides the current room).
Definition at line 19 of file MiniMapManager.cs.
Referenced by Awake(), InitWhenReady(), and UpdatePlayerIcon().
lineOffset
Vector2 Manager.MiniMapManager.lineOffset = new(8f, 8f) private
Small offset applied to the start position of each connection line.
Definition at line 71 of file MiniMapManager.cs.
Referenced by GenerateConnections().
linePrefab
GameObject Manager.MiniMapManager.linePrefab private
Prefab used for connection lines between rooms.
Definition at line 60 of file MiniMapManager.cs.
Referenced by GenerateConnections().
lineThickness
float Manager.MiniMapManager.lineThickness = 2f private
Line thickness for connections.
Definition at line 65 of file MiniMapManager.cs.
Referenced by GenerateConnections().
minimapRect
RectTransform Manager.MiniMapManager.minimapRect private
Root RectTransform of the minimap UI.
Definition at line 30 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons().
playerIcon
RectTransform Manager.MiniMapManager.playerIcon private
RectTransform of the player icon root.
Definition at line 45 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons().
playerIconVisual
RectTransform Manager.MiniMapManager.playerIconVisual private
Visual part of the player icon (rotated to show facing).
Definition at line 50 of file MiniMapManager.cs.
Referenced by UpdatePlayerIcon().
roomIconPrefab
GameObject Manager.MiniMapManager.roomIconPrefab private
Prefab used for each room icon.
Definition at line 55 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons().
roomsContainer
RectTransform Manager.MiniMapManager.roomsContainer private
Parent container for room icons.
Definition at line 35 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons().
unvisitedColor
Color Manager.MiniMapManager.unvisitedColor = new(0.5f, 0.5f, 0.5f) private
Color for unvisited rooms.
Definition at line 82 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons(), and RefreshRoomStates().
visitedColor
Color Manager.MiniMapManager.visitedColor = Color.white private
Color for visited rooms.
Definition at line 77 of file MiniMapManager.cs.
Referenced by GenerateRoomIcons(), and RefreshRoomStates().
voronoiGenerator
VoronoiGenerator Manager.MiniMapManager.voronoiGenerator private
Reference to the Voronoi generator (provides the dungeon graph and size).
Definition at line 24 of file MiniMapManager.cs.
Referenced by Awake(), and InitWhenReady().
The documentation for this class was generated from the following file:
MiniMapManager.cs