Projektarbeit 24/25: Manager.CameraManager Class Reference
Manager.CameraManager Class Reference
Manages camera switching between first-person and canvas views and enables the corresponding player movement controls.
Public Member Functions
void SetActiveCanvas (CanvasDraw canvas)
Sets the currently active canvas drawing component.
void SetPlayer (GameObject player)
Assigns the player references (camera and controller) and enters first-person view.
void SetCanvasTarget (Transform target)
Moves the canvas camera to look at a target (e.g., the drawing center).
Properties
static CameraManager Instance [get, private set]
Singleton instance of the CameraManager.
static CanvasDraw ActiveCanvasDraw [get, private set]
Currently active canvas drawing component, if any.
Private Member Functions
void Awake ()
Initializes the singleton instance.
void Update ()
Allows switching back to FirstPersonView via a key.
void SetFirstPersonView ()
Activates the first-person camera and enables player movement.
void SetCanvView ()
Activates the canvas camera and disables player movement.
void SetPlayerVisible (bool visible)
Shows or hides all Renderer components of the player.
void OnEnable ()
Subscribes to the OnActivateCanvasView event.
void OnDisable ()
Unsubscribes from the OnActivateCanvasView event.
Private Attributes
KeyCode switchKey = KeyCode.Tab
Key to switch back to the first-person view.
CinemachineCamera canvCamera
Cinemachine camera used for the canvas view.
CinemachineCamera _firstPersonCamera
Player’s first-person Cinemachine camera.
FirstPersonPlayerController _firstPersonPlayerController
Player movement/controller script.
GameObject _player
Player GameObject.
Detailed Description
Manages camera switching between first-person and canvas views and enables the corresponding player movement controls.
Definition at line 11 of file CameraManager.cs.
Member Function Documentation
Awake()
void Manager.CameraManager.Awake () inline private
Initializes the singleton instance.
Definition at line 53 of file CameraManager.cs.
References Instance.
OnDisable()
void Manager.CameraManager.OnDisable () inline private
Unsubscribes from the OnActivateCanvasView event.
Definition at line 182 of file CameraManager.cs.
References Manager.EventManager.OnActivateCanvasView, and SetCanvView().
OnEnable()
void Manager.CameraManager.OnEnable () inline private
Subscribes to the OnActivateCanvasView event.
Definition at line 174 of file CameraManager.cs.
References Manager.EventManager.OnActivateCanvasView, and SetCanvView().
SetActiveCanvas()
void Manager.CameraManager.SetActiveCanvas (CanvasDraw canvas) inline
Sets the currently active canvas drawing component.
Parameters
canvas CanvasDraw to mark as active.
Definition at line 79 of file CameraManager.cs.
References ActiveCanvasDraw.
Referenced by MiniGame.DrawingTrigger.Interact().
SetCanvasTarget()
void Manager.CameraManager.SetCanvasTarget (Transform target) inline
Moves the canvas camera to look at a target (e.g., the drawing center).
Parameters
target Transform to focus and face.
Definition at line 154 of file CameraManager.cs.
References canvCamera.
Referenced by MiniGame.DrawingTrigger.Interact().
SetCanvView()
void Manager.CameraManager.SetCanvView () inline private
Activates the canvas camera and disables player movement.
Definition at line 119 of file CameraManager.cs.
References canvCamera, Manager.GameInputManager.Instance, Manager.GameInputManager.MouseLocked(), SetPlayerVisible(), and MiniGame.CanvasDraw.ToDraw.
Referenced by OnDisable(), and OnEnable().
SetFirstPersonView()
void Manager.CameraManager.SetFirstPersonView () inline private
Activates the first-person camera and enables player movement.
Definition at line 101 of file CameraManager.cs.
References canvCamera, Manager.GameInputManager.Instance, Manager.GameInputManager.MouseLocked(), SetPlayerVisible(), and MiniGame.CanvasDraw.ToDraw.
Referenced by SetPlayer(), and Update().
SetPlayer()
void Manager.CameraManager.SetPlayer (GameObject player) inline
Assigns the player references (camera and controller) and enters first-person view.
Parameters
player The player GameObject.
Definition at line 88 of file CameraManager.cs.
References _firstPersonCamera, _firstPersonPlayerController, _player, and SetFirstPersonView().
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
SetPlayerVisible()
void Manager.CameraManager.SetPlayerVisible (bool visible) inline private
Shows or hides all Renderer components of the player.
Parameters
visible Whether the player should be visible.
Definition at line 138 of file CameraManager.cs.
References _player.
Referenced by SetCanvView(), and SetFirstPersonView().
Update()
void Manager.CameraManager.Update () inline private
Allows switching back to FirstPersonView via a key.
Definition at line 67 of file CameraManager.cs.
References SetFirstPersonView(), and switchKey.
Member Data Documentation
_firstPersonCamera
CinemachineCamera Manager.CameraManager._firstPersonCamera private
Player’s first-person Cinemachine camera.
Definition at line 38 of file CameraManager.cs.
Referenced by SetPlayer().
_firstPersonPlayerController
FirstPersonPlayerController Manager.CameraManager._firstPersonPlayerController private
Player movement/controller script.
Definition at line 43 of file CameraManager.cs.
Referenced by SetPlayer().
_player
GameObject Manager.CameraManager._player private
Player GameObject.
Definition at line 48 of file CameraManager.cs.
Referenced by SetPlayer(), and SetPlayerVisible().
canvCamera
CinemachineCamera Manager.CameraManager.canvCamera private
Cinemachine camera used for the canvas view.
Definition at line 33 of file CameraManager.cs.
Referenced by SetCanvasTarget(), SetCanvView(), and SetFirstPersonView().
switchKey
KeyCode Manager.CameraManager.switchKey = KeyCode.Tab private
Key to switch back to the first-person view.
Definition at line 27 of file CameraManager.cs.
Referenced by Update().
Property Documentation
ActiveCanvasDraw
CanvasDraw Manager.CameraManager.ActiveCanvasDraw static get private set
Currently active canvas drawing component, if any.
Definition at line 21 of file CameraManager.cs.
Referenced by MiniGame.DrawingTrigger.Interact(), SetActiveCanvas(), and MiniGame.CanvasDraw.Update().
Instance
CameraManager Manager.CameraManager.Instance static get private set
Singleton instance of the CameraManager.
Definition at line 16 of file CameraManager.cs.
Referenced by Awake(), MiniGame.DrawingTrigger.Interact(), and Manager.GameManagerVoronoi.SpawnPlayer().
The documentation for this class was generated from the following file:
CameraManager.cs