Projektarbeit 24/25: Dungeon.Triangle Class Reference
Dungeon.Triangle Class Reference
Simple triangle helper built from three points. Stores its edges/points and provides circle/intersection checks.
Public Member Functions
Triangle (Point a, Point b, Point c)
Creates a triangle from three points (A, B, C) and builds its three edges.
bool IsInCircumcircle (Point p)
Checks whether a given point lies inside this triangle's circumcircle.
bool ContainsPoints (List< Point > points)
Checks whether any point in the given list is one of this triangle's corners.
bool ContainsEdge (Edge edge)
Checks whether the given edge is one of this triangle's edges.
Circle GetCircumcircle ()
Calculates this triangle's circumcircle (center and radius).
void PrintTriangle ()
Logs a readable string with the triangle's three corner coordinates.
Static Public Member Functions
static Point GetIntersection (Edge e1, Edge e2)
Calculates the intersection point of two lines (if it exists), the method is mainly used to get the center of the circumcircle (and there should always be an intersection of two bisectors of the triangle edges)
Public Attributes
List< Edge > Edges
The three edges that form this triangle.
List< Point > Points
The three corner points of this triangle, in order A, B, C.
Detailed Description
Simple triangle helper built from three points. Stores its edges/points and provides circle/intersection checks.
Definition at line 11 of file Geometry.cs.
Constructor & Destructor Documentation
Triangle()
Dungeon.Triangle.Triangle (Point a, Point b, Point c) inline
Creates a triangle from three points (A, B, C) and builds its three edges.
Parameters
a Corner A.
b Corner B.
c Corner C.
Definition at line 29 of file Geometry.cs.
References Edges, and Points.
Member Function Documentation
ContainsEdge()
bool Dungeon.Triangle.ContainsEdge (Edge edge) inline
Checks whether the given edge is one of this triangle's edges.
Parameters
edge Edge to test.
Returns
True if it matches any of the three edges.
Definition at line 94 of file Geometry.cs.
References Edges, and Dungeon.Edge.Equals().
ContainsPoints()
bool Dungeon.Triangle.ContainsPoints (List< Point > points) inline
Checks whether any point in the given list is one of this triangle's corners.
Parameters
points The List of points to check
Returns
True if at least one point is a corner of the triangle
Definition at line 66 of file Geometry.cs.
References Dungeon.Point.Equals(), and Points.
GetCircumcircle()
Circle Dungeon.Triangle.GetCircumcircle () inline
Calculates this triangle's circumcircle (center and radius).
Returns
The circumcircle.
Definition at line 118 of file Geometry.cs.
References Points.
Referenced by IsInCircumcircle().
GetIntersection()
Point Dungeon.Triangle.GetIntersection (Edge e1, Edge e2) inline static
Calculates the intersection point of two lines (if it exists), the method is mainly used to get the center of the circumcircle (and there should always be an intersection of two bisectors of the triangle edges)
Parameters
e1 First edge
e2 Second edge
Returns
The intersection point, or null if both are vertical.
Definition at line 143 of file Geometry.cs.
References Dungeon.Edge.A, Dungeon.Edge.B, Dungeon.Point.X, and Dungeon.Point.Y.
IsInCircumcircle()
bool Dungeon.Triangle.IsInCircumcircle (Point p) inline
Checks whether a given point lies inside this triangle's circumcircle.
Parameters
p Point to test.
Returns
True if inside, otherwise false.
Definition at line 48 of file Geometry.cs.
References GetCircumcircle(), Dungeon.Point.X, and Dungeon.Point.Y.
PrintTriangle()
void Dungeon.Triangle.PrintTriangle () inline
Logs a readable string with the triangle's three corner coordinates.
Definition at line 206 of file Geometry.cs.
References Points.
Member Data Documentation
Edges
List<Edge> Dungeon.Triangle.Edges
The three edges that form this triangle.
Definition at line 16 of file Geometry.cs.
Referenced by ContainsEdge(), and Triangle().
Points
List<Point> Dungeon.Triangle.Points
The three corner points of this triangle, in order A, B, C.
Definition at line 21 of file Geometry.cs.
Referenced by ContainsPoints(), GetCircumcircle(), PrintTriangle(), and Triangle().
The documentation for this class was generated from the following file:
Geometry.cs