Projektarbeit 24/25: Manager.QuestionManager Class Reference
Manager.QuestionManager Class Reference
Manages a list of questions, selects a random question, and checks player answers.
Public Member Functions
void Start ()
Initialize the question manager, load questions, and pick a random question at start.
void LoadQuestions ()
Loads the questions into the list. Can be extended to load from a file or database.
void AskRandomQuestion ()
Selects a random question from the question list.
bool CheckAnswer (int predictedDigit)
Checks if the predicted digit matches the current question's answer.
string GetCurrentQuestionText ()
Returns the text of the current question for UI display.
Public Attributes
List< Question > questions = new List<Question>()
List of all available questions.
Private Attributes
Question _currentQuestion
The currently active question.
Detailed Description
Manages a list of questions, selects a random question, and checks player answers.
Definition at line 38 of file QuestionManager.cs.
Member Function Documentation
AskRandomQuestion()
void Manager.QuestionManager.AskRandomQuestion () inline
Selects a random question from the question list.
Definition at line 114 of file QuestionManager.cs.
References _currentQuestion, and questions.
Referenced by Start().
CheckAnswer()
bool Manager.QuestionManager.CheckAnswer (int predictedDigit) inline
Checks if the predicted digit matches the current question's answer.
Parameters
predictedDigit The player's predicted digit.
Returns
True if correct, false otherwise.
Definition at line 126 of file QuestionManager.cs.
References _currentQuestion.
GetCurrentQuestionText()
string Manager.QuestionManager.GetCurrentQuestionText () inline
Returns the text of the current question for UI display.
Returns
The current question's text, or empty string if none.
Definition at line 137 of file QuestionManager.cs.
References _currentQuestion.
LoadQuestions()
void Manager.QuestionManager.LoadQuestions () inline
Loads the questions into the list. Can be extended to load from a file or database.
Definition at line 63 of file QuestionManager.cs.
References questions.
Referenced by Start().
Start()
void Manager.QuestionManager.Start () inline
Initialize the question manager, load questions, and pick a random question at start.
Definition at line 53 of file QuestionManager.cs.
References AskRandomQuestion(), and LoadQuestions().
Member Data Documentation
_currentQuestion
Question Manager.QuestionManager._currentQuestion private
The currently active question.
Definition at line 48 of file QuestionManager.cs.
Referenced by AskRandomQuestion(), CheckAnswer(), and GetCurrentQuestionText().
questions
List<Question> Manager.QuestionManager.questions = new List<Question>()
List of all available questions.
Definition at line 43 of file QuestionManager.cs.
Referenced by AskRandomQuestion(), and LoadQuestions().
The documentation for this class was generated from the following file:
QuestionManager.cs