Projektarbeit 24/25: Dungeon.DungeonGraph Class Reference
Dungeon.DungeonGraph Class Reference
Represents the graph structure of all rooms and their connections in the dungeon.
Public Member Functions
void AddRoom (Room room)
Adds a room to the graph and updates lookups.
List< Room > GetUnvisitedNeighbors (Room room)
Returns all neighbors of a room that were not visited.
void ResetVisited ()
Sets Visited = false on all rooms.
Room GetFarthestRoomFrom (Room start)
Finds the room with the largest distance from a start room.
List< Room > GetAllConnectedRooms (Room start)
Gets all rooms connected to a start room using BFS.
List< Room > FindShortestPath (Room start, Room goal)
Finds the shortest path between two rooms using BFS.
List< Room > FindShortestPathWithoutBossRoom (Room start, Room goal)
Finds the shortest path from start to goal while skipping rooms of type Boss.
Room GetRoomByPoint (Point p)
Gets a room by its center point.
Room GetRoomByID (int id)
Gets a room by its id.
Room GetStartRoom ()
Returns the start room of the dungeon.
Room GetBossRoom ()
Returns the boss room of the dungeon.
List< Room > GetAllEnemyRooms ()
Returns all rooms marked as Enemy type.
List< Room > GetAllMiniGameRooms ()
Returns all rooms marked as MiniGame type.
List< Room > GetAllItemRooms ()
Returns all rooms marked as Item type.
Public Attributes
List< Room > Rooms = new()
All rooms in the dungeon.
Dictionary< int, GameObject > IDDoorDict = new()
Map from room id to its door GameObject.
Private Attributes
Dictionary< Point, Room > _roomDict = new()
Lookup from a room center point to the room.
Dictionary< int, Room > _idDict = new()
Lookup from room id to the room.
Detailed Description
Represents the graph structure of all rooms and their connections in the dungeon.
Definition at line 9 of file DungeonGraph.cs.
Member Function Documentation
AddRoom()
void Dungeon.DungeonGraph.AddRoom (Room room) inline
Adds a room to the graph and updates lookups.
Parameters
room The room to add.
Definition at line 35 of file DungeonGraph.cs.
References _idDict, _roomDict, Dungeon.Room.Center, Dungeon.Room.ID, and Rooms.
FindShortestPath()
List< Room > Dungeon.DungeonGraph.FindShortestPath (Room start, Room goal) inline
Finds the shortest path between two rooms using BFS.
Parameters
start Start room.
goal Target room.
Returns
List of rooms forming the shortest path.
Definition at line 122 of file DungeonGraph.cs.
FindShortestPathWithoutBossRoom()
List< Room > Dungeon.DungeonGraph.FindShortestPathWithoutBossRoom (Room start, Room goal) inline
Finds the shortest path from start to goal while skipping rooms of type Boss.
Parameters
start Start room.
goal Target room.
Returns
List of rooms forming the shortest path.
Definition at line 168 of file DungeonGraph.cs.
GetAllConnectedRooms()
List< Room > Dungeon.DungeonGraph.GetAllConnectedRooms (Room start) inline
Gets all rooms connected to a start room using BFS.
Parameters
start Start room.
Returns
List of connected rooms.
Definition at line 89 of file DungeonGraph.cs.
GetAllEnemyRooms()
List< Room > Dungeon.DungeonGraph.GetAllEnemyRooms () inline
Returns all rooms marked as Enemy type.
Returns
List of enemy rooms.
Definition at line 252 of file DungeonGraph.cs.
References Rooms.
GetAllItemRooms()
List< Room > Dungeon.DungeonGraph.GetAllItemRooms () inline
Returns all rooms marked as Item type.
Returns
List of item rooms.
Definition at line 270 of file DungeonGraph.cs.
References Rooms.
GetAllMiniGameRooms()
List< Room > Dungeon.DungeonGraph.GetAllMiniGameRooms () inline
Returns all rooms marked as MiniGame type.
Returns
List of minigame rooms.
Definition at line 261 of file DungeonGraph.cs.
References Rooms.
GetBossRoom()
Room Dungeon.DungeonGraph.GetBossRoom () inline
Returns the boss room of the dungeon.
Returns
The boss room.
Definition at line 243 of file DungeonGraph.cs.
References Rooms.
GetFarthestRoomFrom()
Room Dungeon.DungeonGraph.GetFarthestRoomFrom (Room start) inline
Finds the room with the largest distance from a start room.
Parameters
start Room to measure from.
Returns
The farthest room.
Definition at line 66 of file DungeonGraph.cs.
References Dungeon.Room.Center, Dungeon.Point.GetDistance(), and Rooms.
GetRoomByID()
Room Dungeon.DungeonGraph.GetRoomByID (int id) inline
Gets a room by its id.
Parameters
id Room id.
Returns
The room, or null.
Definition at line 225 of file DungeonGraph.cs.
References _idDict.
GetRoomByPoint()
Room Dungeon.DungeonGraph.GetRoomByPoint (Point p) inline
Gets a room by its center point.
Parameters
p Center point.
Returns
The room, or null.
Definition at line 215 of file DungeonGraph.cs.
References _roomDict.
GetStartRoom()
Room Dungeon.DungeonGraph.GetStartRoom () inline
Returns the start room of the dungeon.
Returns
The start room.
Definition at line 234 of file DungeonGraph.cs.
References Rooms.
GetUnvisitedNeighbors()
List< Room > Dungeon.DungeonGraph.GetUnvisitedNeighbors (Room room) inline
Returns all neighbors of a room that were not visited.
Parameters
room The room whose neighbors are to be checked.
Returns
List of unvisited neighbors.
Definition at line 47 of file DungeonGraph.cs.
References Dungeon.Room.Neighbors.
ResetVisited()
void Dungeon.DungeonGraph.ResetVisited () inline
Sets Visited = false on all rooms.
Definition at line 55 of file DungeonGraph.cs.
References Rooms.
Member Data Documentation
_idDict
Dictionary<int, Room> Dungeon.DungeonGraph._idDict = new() private
Lookup from room id to the room.
Definition at line 29 of file DungeonGraph.cs.
Referenced by AddRoom(), and GetRoomByID().
_roomDict
Dictionary<Point, Room> Dungeon.DungeonGraph._roomDict = new() private
Lookup from a room center point to the room.
Definition at line 24 of file DungeonGraph.cs.
Referenced by AddRoom(), and GetRoomByPoint().
IDDoorDict
Dictionary<int, GameObject> Dungeon.DungeonGraph.IDDoorDict = new()
Map from room id to its door GameObject.
Definition at line 19 of file DungeonGraph.cs.
Rooms
List<Room> Dungeon.DungeonGraph.Rooms = new()
All rooms in the dungeon.
Definition at line 14 of file DungeonGraph.cs.
Referenced by AddRoom(), GetAllEnemyRooms(), GetAllItemRooms(), GetAllMiniGameRooms(), GetBossRoom(), GetFarthestRoomFrom(), GetStartRoom(), and ResetVisited().
The documentation for this class was generated from the following file:
DungeonGraph.cs