Projektarbeit 24/25: Shooting.PlayerShooting Class Reference
Shooting.PlayerShooting Class Reference
Handles player shooting by getting projectiles from a pool and spawning them at the shoot point.
Public Member Functions
void Init (ObjectPoolManager poolManager)
Sets the object pool manager at runtime.
Private Member Functions
void Update ()
Checks input each frame and fires when the fire button ("Spacebar") is pressed.
void FireProjectile ()
Fires a projectile by retrieving one from the object pool and activating it at the shooting point.
Private Attributes
ObjectPoolManager objectPoolManager
Reference to the object pool manager that provides projectiles.
Transform shootPoint
Point where projectiles are spawned.
Detailed Description
Handles player shooting by getting projectiles from a pool and spawning them at the shoot point.
Definition at line 9 of file PlayerShooting.cs.
Member Function Documentation
FireProjectile()
void Shooting.PlayerShooting.FireProjectile () inline private
Fires a projectile by retrieving one from the object pool and activating it at the shooting point.
Definition at line 35 of file PlayerShooting.cs.
References objectPoolManager, and shootPoint.
Referenced by Update().
Init()
void Shooting.PlayerShooting.Init (ObjectPoolManager poolManager) inline
Sets the object pool manager at runtime.
Parameters
poolManager Pool manager to use.
Definition at line 50 of file PlayerShooting.cs.
References objectPoolManager.
Referenced by Manager.GameManagerVoronoi.SpawnPlayer().
Update()
void Shooting.PlayerShooting.Update () inline private
Checks input each frame and fires when the fire button ("Spacebar") is pressed.
Definition at line 24 of file PlayerShooting.cs.
References FireProjectile().
Member Data Documentation
objectPoolManager
ObjectPoolManager Shooting.PlayerShooting.objectPoolManager private
Reference to the object pool manager that provides projectiles.
Definition at line 14 of file PlayerShooting.cs.
Referenced by FireProjectile(), and Init().
shootPoint
Transform Shooting.PlayerShooting.shootPoint private
Point where projectiles are spawned.
Definition at line 19 of file PlayerShooting.cs.
Referenced by FireProjectile().
The documentation for this class was generated from the following file:
PlayerShooting.cs