Projektarbeit 24/25: Stats.Stats Class Reference
Stats.Stats Class Reference
The Stats-Class is used to keep track of an objects Health, Damage and Speed (and possibly more in the future).
Public Member Functions
List< float > GetMaxStatsList ()
Getter method for the list of maximum stats.
List< float > GetCurStatsList ()
Getter method for the list of current stats.
void SetStats (List< float > cur, List< float > max)
With this method it is possible to set the values of both lists through the script instead of the serialize field.
float GetMaxStats (int stat)
Getter method for a specific maximum stat.
float GetCurStats (int stat)
Getter method for a specific current stat.
void IncreaseMaxStat (int stat, float amount)
Increases a maximum stat by a specific value.
void DecreaseMaxStat (int stat, float amount)
Decreases a maximum stat by a specific value or sets it to 0 if the value goes into the negative. It also sets the current stat if the current stat is higher than the new maximum stat value.
void IncreaseCurStat (int stat, float amount)
Increases a current stat by a specific value.
void DecreaseCurStat (int stat, float amount)
Decreases a current stat by a specific value or sets it to 0 if the value goes into the negative.
void AddToMaxPreserveRatio (int stat, float delta)
The Method is used to change a stat while keeping the percentage between maximum and current stat the same.
Private Attributes
List< float > maxStats = new List<float>()
List< float > curStats = new List<float>()
Detailed Description
The Stats-Class is used to keep track of an objects Health, Damage and Speed (and possibly more in the future).
Definition at line 9 of file Stats.cs.
Member Function Documentation
AddToMaxPreserveRatio()
void Stats.Stats.AddToMaxPreserveRatio (int stat, float delta) inline
The Method is used to change a stat while keeping the percentage between maximum and current stat the same.
Parameters
stat Index of the stat you want to change.
delta The value by which the stats should be changed.
Definition at line 134 of file Stats.cs.
References curStats, and maxStats.
Referenced by Items.Equipment.Use().
DecreaseCurStat()
void Stats.Stats.DecreaseCurStat (int stat, float amount) inline
Decreases a current stat by a specific value or sets it to 0 if the value goes into the negative.
Parameters
stat The index of the stat you want to decrease.
amount The float value by which the stat shall be decreased.
Definition at line 119 of file Stats.cs.
References curStats.
Referenced by Interaction.PlayerInteraction.OnCollisionEnter().
DecreaseMaxStat()
void Stats.Stats.DecreaseMaxStat (int stat, float amount) inline
Decreases a maximum stat by a specific value or sets it to 0 if the value goes into the negative. It also sets the current stat if the current stat is higher than the new maximum stat value.
Parameters
stat The index of the stat you want to decrease.
amount The float value by which the stat shall be decreased.
Definition at line 84 of file Stats.cs.
References curStats, and maxStats.
GetCurStats()
float Stats.Stats.GetCurStats (int stat) inline
Getter method for a specific current stat.
Parameters
stat The index of the stat you want to get.
Returns
The float value of the wanted stat.
Definition at line 63 of file Stats.cs.
References curStats.
Referenced by Interaction.EnemyInteraction.Interact(), Interaction.EnemyInteraction.OnCollisionEnter(), and Manager.UIManager.Update().
GetCurStatsList()
List< float > Stats.Stats.GetCurStatsList ()
Getter method for the list of current stats.
Returns
The list "curStats"
References curStats.
Referenced by Interaction.LevelExitInteraction.Interact().
GetMaxStats()
float Stats.Stats.GetMaxStats (int stat) inline
Getter method for a specific maximum stat.
Parameters
stat The index of the stat you want to get.
Returns
The float value of the wanted stat.
Definition at line 53 of file Stats.cs.
References maxStats.
GetMaxStatsList()
List< float > Stats.Stats.GetMaxStatsList ()
Getter method for the list of maximum stats.
Returns
The list "maxStats"
References maxStats.
IncreaseCurStat()
void Stats.Stats.IncreaseCurStat (int stat, float amount) inline
Increases a current stat by a specific value.
Parameters
stat The index of the stat you want to increase.
amount The float value by which the stat shall be increased.
Definition at line 105 of file Stats.cs.
References curStats, and maxStats.
IncreaseMaxStat()
void Stats.Stats.IncreaseMaxStat (int stat, float amount) inline
Increases a maximum stat by a specific value.
Parameters
stat The index of the stat you want to increase.
amount The float value by which the stat shall be increased.
Definition at line 73 of file Stats.cs.
References maxStats.
SetStats()
void Stats.Stats.SetStats (List< float > cur, List< float > max) inline
With this method it is possible to set the values of both lists through the script instead of the serialize field.
Parameters
cur A float list of the new values for the current stats.
max A float list of the new values for the maximum stats.
Definition at line 42 of file Stats.cs.
References curStats, and maxStats.
Member Data Documentation
curStats
List<float> Stats.Stats.curStats = new List<float>() private
Definition at line 23 of file Stats.cs.
Referenced by AddToMaxPreserveRatio(), DecreaseCurStat(), DecreaseMaxStat(), GetCurStats(), GetCurStatsList(), IncreaseCurStat(), and SetStats().
maxStats
List<float> Stats.Stats.maxStats = new List<float>() private
Definition at line 19 of file Stats.cs.
Referenced by AddToMaxPreserveRatio(), DecreaseMaxStat(), GetMaxStats(), GetMaxStatsList(), IncreaseCurStat(), IncreaseMaxStat(), and SetStats().
The documentation for this class was generated from the following file:
Stats.cs